//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sat Nov  8 04:56:21 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// calculate                      O    25
// RDY_calculate                  O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// calculate_a                    I    24
// calculate_b                    I    24
// calculate_cin                  I     1
//
// Combinational paths from inputs to outputs:
//   (calculate_a, calculate_b, calculate_cin) -> calculate
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkBrentKungAdder24(CLK,
			  RST_N,

			  calculate_a,
			  calculate_b,
			  calculate_cin,
			  calculate,
			  RDY_calculate);
  input  CLK;
  input  RST_N;

  // value method calculate
  input  [23 : 0] calculate_a;
  input  [23 : 0] calculate_b;
  input  calculate_cin;
  output [24 : 0] calculate;
  output RDY_calculate;

  // signals for module outputs
  wire [24 : 0] calculate;
  wire RDY_calculate;

  // remaining internal signals
  wire [24 : 0] IF_calculate_cin_THEN_1_ELSE_0__q1;
  wire [23 : 0] IF_x366_XOR_IF_calculate_cin_THEN_1_ELSE_0_BIT_ETC__q2,
		sum__h27;
  wire [21 : 0] calculate_a_BIT_21_XOR_calculate_b_BIT_21_1_XO_ETC___d237;
  wire [19 : 0] calculate_a_BIT_19_9_XOR_calculate_b_BIT_19_0__ETC___d236;
  wire [17 : 0] calculate_a_BIT_17_0_XOR_calculate_b_BIT_17_1__ETC___d235;
  wire [15 : 0] calculate_a_BIT_15_4_XOR_calculate_b_BIT_15_5__ETC___d234;
  wire [13 : 0] calculate_a_BIT_13_5_XOR_calculate_b_BIT_13_6__ETC___d233;
  wire [11 : 0] calculate_a_BIT_11_9_XOR_calculate_b_BIT_11_0__ETC___d232;
  wire [9 : 0] calculate_a_BIT_9_0_XOR_calculate_b_BIT_9_1_3__ETC___d231;
  wire [7 : 0] calculate_a_BIT_7_7_XOR_calculate_b_BIT_7_8_00_ETC___d230;
  wire [5 : 0] calculate_a_BIT_5_08_XOR_calculate_b_BIT_5_09__ETC___d229;
  wire [3 : 0] calculate_a_BIT_3_22_XOR_calculate_b_BIT_3_23__ETC___d228;
  wire [1 : 0] calculate_a_BIT_1_33_XOR_calculate_b_BIT_1_34__ETC___d227;
  wire carry_in__h1889,
       carry_in__h2422,
       carry_in__h2769,
       carry_in__h3626,
       carry_in__h3778,
       carry_in__h4016,
       carry_in__h4363,
       carry_in__h5322,
       carry_in__h5712,
       carry_in__h6059,
       carry_in__h6211,
       cout__h26,
       x__h1366,
       x__h1419,
       x__h1721,
       x__h1834,
       x__h1836,
       x__h2042,
       x__h2212,
       x__h2241,
       x__h2354,
       x__h2357,
       x__h2368,
       x__h2575,
       x__h2602,
       x__h2715,
       x__h2717,
       x__h2922,
       x__h3026,
       x__h3055,
       x__h3084,
       x__h3197,
       x__h3200,
       x__h3211,
       x__h3225,
       x__h3432,
       x__h3459,
       x__h3572,
       x__h3574,
       x__h3779,
       x__h3806,
       x__h3835,
       x__h3948,
       x__h3951,
       x__h3962,
       x__h4169,
       x__h4196,
       x__h4309,
       x__h4311,
       x__h4516,
       x__h4564,
       x__h4693,
       x__h4722,
       x__h4751,
       x__h4864,
       x__h4867,
       x__h4878,
       x__h4892,
       x__h4921,
       x__h5128,
       x__h5155,
       x__h5268,
       x__h5270,
       x__h5475,
       x__h5502,
       x__h5531,
       x__h5644,
       x__h5647,
       x__h5658,
       x__h5865,
       x__h5892,
       x__h6005,
       x__h6007,
       x__h6212,
       x__h6239,
       x__h6268,
       x__h6297,
       x__h6410,
       x__h6413,
       x__h6424,
       x__h6438,
       y__h1313,
       y__h1420,
       y__h1722,
       y__h1780,
       y__h1891,
       y__h2043,
       y__h2213,
       y__h2242,
       y__h2300,
       y__h2358,
       y__h2424,
       y__h2576,
       y__h2603,
       y__h2661,
       y__h2718,
       y__h2771,
       y__h2923,
       y__h3027,
       y__h3056,
       y__h3085,
       y__h3143,
       y__h3201,
       y__h3281,
       y__h3433,
       y__h3460,
       y__h3518,
       y__h3575,
       y__h3628,
       y__h3780,
       y__h3807,
       y__h3836,
       y__h3894,
       y__h3952,
       y__h4018,
       y__h4170,
       y__h4197,
       y__h4255,
       y__h4312,
       y__h4365,
       y__h4517,
       y__h4565,
       y__h4694,
       y__h4723,
       y__h4752,
       y__h4810,
       y__h4868,
       y__h4977,
       y__h5129,
       y__h5156,
       y__h5214,
       y__h5271,
       y__h5324,
       y__h5476,
       y__h5503,
       y__h5532,
       y__h5590,
       y__h5648,
       y__h5714,
       y__h5866,
       y__h5893,
       y__h5951,
       y__h6008,
       y__h6061,
       y__h6213,
       y__h6240,
       y__h6269,
       y__h6298,
       y__h6356,
       y__h6414;

  // value method calculate
  assign calculate = { sum__h27, cout__h26 } ;
  assign RDY_calculate = 1'd1 ;

  // remaining internal signals
  assign IF_calculate_cin_THEN_1_ELSE_0__q1 = calculate_cin ? 25'd1 : 25'd0 ;
  assign IF_x366_XOR_IF_calculate_cin_THEN_1_ELSE_0_BIT_ETC__q2 =
	     (x__h1366 ^ IF_calculate_cin_THEN_1_ELSE_0__q1[0]) ?
	       24'd1 :
	       24'd0 ;
  assign calculate_a_BIT_11_9_XOR_calculate_b_BIT_11_0__ETC___d232 =
	     { x__h3951 ^ (y__h3894 | y__h3628),
	       y__h3952 ^ carry_in__h3626,
	       calculate_a_BIT_9_0_XOR_calculate_b_BIT_9_1_3__ETC___d231 } ;
  assign calculate_a_BIT_13_5_XOR_calculate_b_BIT_13_6__ETC___d233 =
	     { x__h4311 ^ (y__h4255 | y__h4018),
	       y__h4312 ^ carry_in__h4016,
	       calculate_a_BIT_11_9_XOR_calculate_b_BIT_11_0__ETC___d232 } ;
  assign calculate_a_BIT_15_4_XOR_calculate_b_BIT_15_5__ETC___d234 =
	     { x__h4867 ^ (y__h4810 | y__h4365),
	       y__h4868 ^ carry_in__h4363,
	       calculate_a_BIT_13_5_XOR_calculate_b_BIT_13_6__ETC___d233 } ;
  assign calculate_a_BIT_17_0_XOR_calculate_b_BIT_17_1__ETC___d235 =
	     { x__h5270 ^ (y__h5214 | y__h4977),
	       y__h5271 ^ carry_in__h6211,
	       calculate_a_BIT_15_4_XOR_calculate_b_BIT_15_5__ETC___d234 } ;
  assign calculate_a_BIT_19_9_XOR_calculate_b_BIT_19_0__ETC___d236 =
	     { x__h5647 ^ (y__h5590 | y__h5324),
	       y__h5648 ^ carry_in__h5322,
	       calculate_a_BIT_17_0_XOR_calculate_b_BIT_17_1__ETC___d235 } ;
  assign calculate_a_BIT_1_33_XOR_calculate_b_BIT_1_34__ETC___d227 =
	     { x__h1836 ^ (y__h1780 | y__h1313),
	       IF_x366_XOR_IF_calculate_cin_THEN_1_ELSE_0_BIT_ETC__q2[0] } ;
  assign calculate_a_BIT_21_XOR_calculate_b_BIT_21_1_XO_ETC___d237 =
	     { x__h6007 ^ (y__h5951 | y__h5714),
	       y__h6008 ^ carry_in__h5712,
	       calculate_a_BIT_19_9_XOR_calculate_b_BIT_19_0__ETC___d236 } ;
  assign calculate_a_BIT_3_22_XOR_calculate_b_BIT_3_23__ETC___d228 =
	     { x__h2357 ^ (y__h2300 | y__h1891),
	       y__h2358 ^ carry_in__h1889,
	       calculate_a_BIT_1_33_XOR_calculate_b_BIT_1_34__ETC___d227 } ;
  assign calculate_a_BIT_5_08_XOR_calculate_b_BIT_5_09__ETC___d229 =
	     { x__h2717 ^ (y__h2661 | y__h2424),
	       y__h2718 ^ carry_in__h2422,
	       calculate_a_BIT_3_22_XOR_calculate_b_BIT_3_23__ETC___d228 } ;
  assign calculate_a_BIT_7_7_XOR_calculate_b_BIT_7_8_00_ETC___d230 =
	     { x__h3200 ^ (y__h3143 | y__h2771),
	       y__h3201 ^ carry_in__h2769,
	       calculate_a_BIT_5_08_XOR_calculate_b_BIT_5_09__ETC___d229 } ;
  assign calculate_a_BIT_9_0_XOR_calculate_b_BIT_9_1_3__ETC___d231 =
	     { x__h3574 ^ (y__h3518 | y__h3281),
	       y__h3575 ^ carry_in__h3778,
	       calculate_a_BIT_7_7_XOR_calculate_b_BIT_7_8_00_ETC___d230 } ;
  assign carry_in__h1889 = x__h1419 | y__h1420 ;
  assign carry_in__h2422 = x__h2042 | y__h2043 ;
  assign carry_in__h2769 = x__h2575 | y__h2576 ;
  assign carry_in__h3626 = x__h3432 | y__h3433 ;
  assign carry_in__h3778 = x__h2922 | y__h2923 ;
  assign carry_in__h4016 = x__h3779 | y__h3780 ;
  assign carry_in__h4363 = x__h4169 | y__h4170 ;
  assign carry_in__h5322 = x__h5128 | y__h5129 ;
  assign carry_in__h5712 = x__h5475 | y__h5476 ;
  assign carry_in__h6059 = x__h5865 | y__h5866 ;
  assign carry_in__h6211 = x__h4516 | y__h4517 ;
  assign cout__h26 = x__h6212 | y__h6213 ;
  assign sum__h27 =
	     { x__h6413 ^ (y__h6356 | y__h6061),
	       y__h6414 ^ carry_in__h6059,
	       calculate_a_BIT_21_XOR_calculate_b_BIT_21_1_XO_ETC___d237 } ;
  assign x__h1366 = calculate_a[0] ^ calculate_b[0] ;
  assign x__h1419 = x__h1721 | y__h1722 ;
  assign x__h1721 = calculate_a[1] & calculate_b[1] ;
  assign x__h1834 = x__h1836 & x__h1366 ;
  assign x__h1836 = calculate_a[1] ^ calculate_b[1] ;
  assign x__h2042 = x__h2212 | y__h2213 ;
  assign x__h2212 = x__h2241 | y__h2242 ;
  assign x__h2241 = calculate_a[3] & calculate_b[3] ;
  assign x__h2354 = x__h2357 & y__h2358 ;
  assign x__h2357 = calculate_a[3] ^ calculate_b[3] ;
  assign x__h2368 = x__h2354 & x__h1834 ;
  assign x__h2575 = x__h2602 | y__h2603 ;
  assign x__h2602 = calculate_a[5] & calculate_b[5] ;
  assign x__h2715 = x__h2717 & y__h2718 ;
  assign x__h2717 = calculate_a[5] ^ calculate_b[5] ;
  assign x__h2922 = x__h3026 | y__h3027 ;
  assign x__h3026 = x__h3055 | y__h3056 ;
  assign x__h3055 = x__h3084 | y__h3085 ;
  assign x__h3084 = calculate_a[7] & calculate_b[7] ;
  assign x__h3197 = x__h3200 & y__h3201 ;
  assign x__h3200 = calculate_a[7] ^ calculate_b[7] ;
  assign x__h3211 = x__h3197 & x__h2715 ;
  assign x__h3225 = x__h3211 & x__h2368 ;
  assign x__h3432 = x__h3459 | y__h3460 ;
  assign x__h3459 = calculate_a[9] & calculate_b[9] ;
  assign x__h3572 = x__h3574 & y__h3575 ;
  assign x__h3574 = calculate_a[9] ^ calculate_b[9] ;
  assign x__h3779 = x__h3806 | y__h3807 ;
  assign x__h3806 = x__h3835 | y__h3836 ;
  assign x__h3835 = calculate_a[11] & calculate_b[11] ;
  assign x__h3948 = x__h3951 & y__h3952 ;
  assign x__h3951 = calculate_a[11] ^ calculate_b[11] ;
  assign x__h3962 = x__h3948 & x__h3572 ;
  assign x__h4169 = x__h4196 | y__h4197 ;
  assign x__h4196 = calculate_a[13] & calculate_b[13] ;
  assign x__h4309 = x__h4311 & y__h4312 ;
  assign x__h4311 = calculate_a[13] ^ calculate_b[13] ;
  assign x__h4516 = x__h4564 | y__h4565 ;
  assign x__h4564 = x__h4693 | y__h4694 ;
  assign x__h4693 = x__h4722 | y__h4723 ;
  assign x__h4722 = x__h4751 | y__h4752 ;
  assign x__h4751 = calculate_a[15] & calculate_b[15] ;
  assign x__h4864 = x__h4867 & y__h4868 ;
  assign x__h4867 = calculate_a[15] ^ calculate_b[15] ;
  assign x__h4878 = x__h4864 & x__h4309 ;
  assign x__h4892 = x__h4878 & x__h3962 ;
  assign x__h4921 = x__h4892 & x__h3225 ;
  assign x__h5128 = x__h5155 | y__h5156 ;
  assign x__h5155 = calculate_a[17] & calculate_b[17] ;
  assign x__h5268 = x__h5270 & y__h5271 ;
  assign x__h5270 = calculate_a[17] ^ calculate_b[17] ;
  assign x__h5475 = x__h5502 | y__h5503 ;
  assign x__h5502 = x__h5531 | y__h5532 ;
  assign x__h5531 = calculate_a[19] & calculate_b[19] ;
  assign x__h5644 = x__h5647 & y__h5648 ;
  assign x__h5647 = calculate_a[19] ^ calculate_b[19] ;
  assign x__h5658 = x__h5644 & x__h5268 ;
  assign x__h5865 = x__h5892 | y__h5893 ;
  assign x__h5892 = calculate_a[21] & calculate_b[21] ;
  assign x__h6005 = x__h6007 & y__h6008 ;
  assign x__h6007 = calculate_a[21] ^ calculate_b[21] ;
  assign x__h6212 = x__h6239 | y__h6240 ;
  assign x__h6239 = x__h6268 | y__h6269 ;
  assign x__h6268 = x__h6297 | y__h6298 ;
  assign x__h6297 = calculate_a[23] & calculate_b[23] ;
  assign x__h6410 = x__h6413 & y__h6414 ;
  assign x__h6413 = calculate_a[23] ^ calculate_b[23] ;
  assign x__h6424 = x__h6410 & x__h6005 ;
  assign x__h6438 = x__h6424 & x__h5658 ;
  assign y__h1313 = x__h1366 & IF_calculate_cin_THEN_1_ELSE_0__q1[0] ;
  assign y__h1420 = x__h1834 & IF_calculate_cin_THEN_1_ELSE_0__q1[0] ;
  assign y__h1722 = x__h1836 & y__h1780 ;
  assign y__h1780 = calculate_a[0] & calculate_b[0] ;
  assign y__h1891 = y__h2358 & carry_in__h1889 ;
  assign y__h2043 = x__h2368 & IF_calculate_cin_THEN_1_ELSE_0__q1[0] ;
  assign y__h2213 = x__h2354 & x__h1419 ;
  assign y__h2242 = x__h2357 & y__h2300 ;
  assign y__h2300 = calculate_a[2] & calculate_b[2] ;
  assign y__h2358 = calculate_a[2] ^ calculate_b[2] ;
  assign y__h2424 = y__h2718 & carry_in__h2422 ;
  assign y__h2576 = x__h2715 & carry_in__h2422 ;
  assign y__h2603 = x__h2717 & y__h2661 ;
  assign y__h2661 = calculate_a[4] & calculate_b[4] ;
  assign y__h2718 = calculate_a[4] ^ calculate_b[4] ;
  assign y__h2771 = y__h3201 & carry_in__h2769 ;
  assign y__h2923 = x__h3225 & IF_calculate_cin_THEN_1_ELSE_0__q1[0] ;
  assign y__h3027 = x__h3211 & x__h2042 ;
  assign y__h3056 = x__h3197 & x__h2575 ;
  assign y__h3085 = x__h3200 & y__h3143 ;
  assign y__h3143 = calculate_a[6] & calculate_b[6] ;
  assign y__h3201 = calculate_a[6] ^ calculate_b[6] ;
  assign y__h3281 = y__h3575 & carry_in__h3778 ;
  assign y__h3433 = x__h3572 & carry_in__h3778 ;
  assign y__h3460 = x__h3574 & y__h3518 ;
  assign y__h3518 = calculate_a[8] & calculate_b[8] ;
  assign y__h3575 = calculate_a[8] ^ calculate_b[8] ;
  assign y__h3628 = y__h3952 & carry_in__h3626 ;
  assign y__h3780 = x__h3962 & carry_in__h3778 ;
  assign y__h3807 = x__h3948 & x__h3432 ;
  assign y__h3836 = x__h3951 & y__h3894 ;
  assign y__h3894 = calculate_a[10] & calculate_b[10] ;
  assign y__h3952 = calculate_a[10] ^ calculate_b[10] ;
  assign y__h4018 = y__h4312 & carry_in__h4016 ;
  assign y__h4170 = x__h4309 & carry_in__h4016 ;
  assign y__h4197 = x__h4311 & y__h4255 ;
  assign y__h4255 = calculate_a[12] & calculate_b[12] ;
  assign y__h4312 = calculate_a[12] ^ calculate_b[12] ;
  assign y__h4365 = y__h4868 & carry_in__h4363 ;
  assign y__h4517 = x__h4921 & IF_calculate_cin_THEN_1_ELSE_0__q1[0] ;
  assign y__h4565 = x__h4892 & x__h2922 ;
  assign y__h4694 = x__h4878 & x__h3779 ;
  assign y__h4723 = x__h4864 & x__h4169 ;
  assign y__h4752 = x__h4867 & y__h4810 ;
  assign y__h4810 = calculate_a[14] & calculate_b[14] ;
  assign y__h4868 = calculate_a[14] ^ calculate_b[14] ;
  assign y__h4977 = y__h5271 & carry_in__h6211 ;
  assign y__h5129 = x__h5268 & carry_in__h6211 ;
  assign y__h5156 = x__h5270 & y__h5214 ;
  assign y__h5214 = calculate_a[16] & calculate_b[16] ;
  assign y__h5271 = calculate_a[16] ^ calculate_b[16] ;
  assign y__h5324 = y__h5648 & carry_in__h5322 ;
  assign y__h5476 = x__h5658 & carry_in__h6211 ;
  assign y__h5503 = x__h5644 & x__h5128 ;
  assign y__h5532 = x__h5647 & y__h5590 ;
  assign y__h5590 = calculate_a[18] & calculate_b[18] ;
  assign y__h5648 = calculate_a[18] ^ calculate_b[18] ;
  assign y__h5714 = y__h6008 & carry_in__h5712 ;
  assign y__h5866 = x__h6005 & carry_in__h5712 ;
  assign y__h5893 = x__h6007 & y__h5951 ;
  assign y__h5951 = calculate_a[20] & calculate_b[20] ;
  assign y__h6008 = calculate_a[20] ^ calculate_b[20] ;
  assign y__h6061 = y__h6414 & carry_in__h6059 ;
  assign y__h6213 = x__h6438 & carry_in__h6211 ;
  assign y__h6240 = x__h6424 & x__h5475 ;
  assign y__h6269 = x__h6410 & x__h5865 ;
  assign y__h6298 = x__h6413 & y__h6356 ;
  assign y__h6356 = calculate_a[22] & calculate_b[22] ;
  assign y__h6414 = calculate_a[22] ^ calculate_b[22] ;
endmodule  // mkBrentKungAdder24

