//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Thu Nov  6 00:21:55 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_match_exponents            O     1 const
// RDY_add_mantissa               O     1 const
// RDY_normalise                  O     1 const
// get_res                        O    32 reg
// RDY_get_res                    O     1 const
// state_1_done                   O     1 reg
// RDY_state_1_done               O     1 const
// state_2_done                   O     1 reg
// RDY_state_2_done               O     1 const
// state_3_done                   O     1 reg
// RDY_state_3_done               O     1 const
// RDY_clear_adder                O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// match_exponents_num1           I    32
// match_exponents_num2           I    32
// EN_match_exponents             I     1
// EN_add_mantissa                I     1
// EN_normalise                   I     1
// EN_clear_adder                 I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFP32_Adder(CLK,
		    RST_N,

		    match_exponents_num1,
		    match_exponents_num2,
		    EN_match_exponents,
		    RDY_match_exponents,

		    EN_add_mantissa,
		    RDY_add_mantissa,

		    EN_normalise,
		    RDY_normalise,

		    get_res,
		    RDY_get_res,

		    state_1_done,
		    RDY_state_1_done,

		    state_2_done,
		    RDY_state_2_done,

		    state_3_done,
		    RDY_state_3_done,

		    EN_clear_adder,
		    RDY_clear_adder);
  input  CLK;
  input  RST_N;

  // action method match_exponents
  input  [31 : 0] match_exponents_num1;
  input  [31 : 0] match_exponents_num2;
  input  EN_match_exponents;
  output RDY_match_exponents;

  // action method add_mantissa
  input  EN_add_mantissa;
  output RDY_add_mantissa;

  // action method normalise
  input  EN_normalise;
  output RDY_normalise;

  // value method get_res
  output [31 : 0] get_res;
  output RDY_get_res;

  // value method state_1_done
  output state_1_done;
  output RDY_state_1_done;

  // value method state_2_done
  output state_2_done;
  output RDY_state_2_done;

  // value method state_3_done
  output state_3_done;
  output RDY_state_3_done;

  // action method clear_adder
  input  EN_clear_adder;
  output RDY_clear_adder;

  // signals for module outputs
  wire [31 : 0] get_res;
  wire RDY_add_mantissa,
       RDY_clear_adder,
       RDY_get_res,
       RDY_match_exponents,
       RDY_normalise,
       RDY_state_1_done,
       RDY_state_2_done,
       RDY_state_3_done,
       state_1_done,
       state_2_done,
       state_3_done;

  // register diff_reg
  reg [7 : 0] diff_reg;
  wire [7 : 0] diff_reg_D_IN;
  wire diff_reg_EN;

  // register done1
  reg done1;
  wire done1_D_IN, done1_EN;

  // register done2
  reg done2;
  wire done2_D_IN, done2_EN;

  // register done3
  reg done3;
  wire done3_D_IN, done3_EN;

  // register final_mantissa
  reg [22 : 0] final_mantissa;
  wire [22 : 0] final_mantissa_D_IN;
  wire final_mantissa_EN;

  // register guard1
  reg guard1;
  wire guard1_D_IN, guard1_EN;

  // register man_carry
  reg man_carry;
  wire man_carry_D_IN, man_carry_EN;

  // register new_exp
  reg [7 : 0] new_exp;
  wire [7 : 0] new_exp_D_IN;
  wire new_exp_EN;

  // register res
  reg [31 : 0] res;
  wire [31 : 0] res_D_IN;
  wire res_EN;

  // register shifted_mantissa_1
  reg [23 : 0] shifted_mantissa_1;
  wire [23 : 0] shifted_mantissa_1_D_IN;
  wire shifted_mantissa_1_EN;

  // register shifted_mantissa_2
  reg [23 : 0] shifted_mantissa_2;
  wire [23 : 0] shifted_mantissa_2_D_IN;
  wire shifted_mantissa_2_EN;

  // register sticky1
  reg sticky1;
  wire sticky1_D_IN, sticky1_EN;

  // ports of submodule rca
  wire [24 : 0] rca_calculate;
  wire [23 : 0] rca_calculate_a, rca_calculate_b;

  // ports of submodule rcs1
  wire [8 : 0] rcs1_calculate;
  wire [7 : 0] rcs1_calculate_a, rcs1_calculate_b;

  // ports of submodule rcs2
  wire [8 : 0] rcs2_calculate;
  wire [7 : 0] rcs2_calculate_a, rcs2_calculate_b;

  // rule scheduling signals
  wire CAN_FIRE_add_mantissa,
       CAN_FIRE_clear_adder,
       CAN_FIRE_match_exponents,
       CAN_FIRE_normalise,
       WILL_FIRE_add_mantissa,
       WILL_FIRE_clear_adder,
       WILL_FIRE_match_exponents,
       WILL_FIRE_normalise;

  // remaining internal signals
  wire [23 : 0] shifted_part__h1062,
		shifted_part__h849,
		sm1__h599,
		sm2__h600,
		y__h1102,
		y__h896,
		y_avValue_snd_snd_fst__h1205,
		y_avValue_snd_snd_fst__h1216,
		y_avValue_snd_snd_snd__h1215;
  wire [22 : 0] IF_guard1_3_OR_sticky1_4_5_OR_rca_calculate_sh_ETC___d60,
		match_exponents_num1_BITS_22_TO_0__q1,
		match_exponents_num2_BITS_22_TO_0__q2,
		x__h1630,
		x__h2055;
  wire [7 : 0] i__h761,
	       i__h996,
	       y__h1104,
	       y__h898,
	       y_avValue_fst__h1161,
	       y_avValue_snd_fst__h1200;
  wire match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3,
       match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5,
       x__h1072,
       x__h741,
       x__h859,
       x__h977;

  // action method match_exponents
  assign RDY_match_exponents = 1'd1 ;
  assign CAN_FIRE_match_exponents = 1'd1 ;
  assign WILL_FIRE_match_exponents = EN_match_exponents ;

  // action method add_mantissa
  assign RDY_add_mantissa = 1'd1 ;
  assign CAN_FIRE_add_mantissa = 1'd1 ;
  assign WILL_FIRE_add_mantissa = EN_add_mantissa ;

  // action method normalise
  assign RDY_normalise = 1'd1 ;
  assign CAN_FIRE_normalise = 1'd1 ;
  assign WILL_FIRE_normalise = EN_normalise ;

  // value method get_res
  assign get_res = res ;
  assign RDY_get_res = 1'd1 ;

  // value method state_1_done
  assign state_1_done = done1 ;
  assign RDY_state_1_done = 1'd1 ;

  // value method state_2_done
  assign state_2_done = done2 ;
  assign RDY_state_2_done = 1'd1 ;

  // value method state_3_done
  assign state_3_done = done3 ;
  assign RDY_state_3_done = 1'd1 ;

  // action method clear_adder
  assign RDY_clear_adder = 1'd1 ;
  assign CAN_FIRE_clear_adder = 1'd1 ;
  assign WILL_FIRE_clear_adder = EN_clear_adder ;

  // submodule rca
  mkRippleCarryAdder rca(.CLK(CLK),
			 .RST_N(RST_N),
			 .calculate_a(rca_calculate_a),
			 .calculate_b(rca_calculate_b),
			 .calculate(rca_calculate),
			 .RDY_calculate());

  // submodule rcs1
  mkRippleCarrySubtractor rcs1(.CLK(CLK),
			       .RST_N(RST_N),
			       .calculate_a(rcs1_calculate_a),
			       .calculate_b(rcs1_calculate_b),
			       .calculate(rcs1_calculate),
			       .RDY_calculate());

  // submodule rcs2
  mkRippleCarrySubtractor rcs2(.CLK(CLK),
			       .RST_N(RST_N),
			       .calculate_a(rcs2_calculate_a),
			       .calculate_b(rcs2_calculate_b),
			       .calculate(rcs2_calculate),
			       .RDY_calculate());

  // register diff_reg
  assign diff_reg_D_IN =
	     match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3 ?
	       8'd0 :
	       y_avValue_fst__h1161 ;
  assign diff_reg_EN = EN_match_exponents ;

  // register done1
  assign done1_D_IN = !EN_clear_adder ;
  assign done1_EN = EN_clear_adder || EN_match_exponents ;

  // register done2
  assign done2_D_IN = !EN_clear_adder ;
  assign done2_EN = EN_clear_adder || EN_add_mantissa ;

  // register done3
  assign done3_D_IN = !EN_clear_adder ;
  assign done3_EN = EN_clear_adder || EN_normalise ;

  // register final_mantissa
  assign final_mantissa_D_IN =
	     rca_calculate[24] ?
	       (rca_calculate[0] ?
		  IF_guard1_3_OR_sticky1_4_5_OR_rca_calculate_sh_ETC___d60 :
		  rca_calculate[23:1]) :
	       (guard1 ?
		  ((sticky1 || rca_calculate[0]) ?
		     x__h2055 :
		     rca_calculate[22:0]) :
		  rca_calculate[22:0]) ;
  assign final_mantissa_EN = EN_add_mantissa ;

  // register guard1
  assign guard1_D_IN =
	     match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5 ?
	       rcs2_calculate[7:0] != 8'd0 && x__h977 :
	       rcs1_calculate[7:0] != 8'd0 && x__h741 ;
  assign guard1_EN =
	     EN_match_exponents &&
	     !match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3 ;

  // register man_carry
  assign man_carry_D_IN = rca_calculate[24] ;
  assign man_carry_EN = EN_add_mantissa ;

  // register new_exp
  assign new_exp_D_IN =
	     match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3 ?
	       match_exponents_num1[30:23] :
	       y_avValue_snd_fst__h1200 ;
  assign new_exp_EN = EN_match_exponents ;

  // register res
  assign res_D_IN =
	     { 1'b1, man_carry ? new_exp + 8'd1 : new_exp, final_mantissa } ;
  assign res_EN = EN_normalise ;

  // register shifted_mantissa_1
  assign shifted_mantissa_1_D_IN =
	     match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3 ?
	       sm1__h599 :
	       y_avValue_snd_snd_fst__h1205 ;
  assign shifted_mantissa_1_EN = EN_match_exponents ;

  // register shifted_mantissa_2
  assign shifted_mantissa_2_D_IN =
	     (match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3 ||
	      match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5) ?
	       sm2__h600 :
	       y_avValue_snd_snd_snd__h1215 ;
  assign shifted_mantissa_2_EN = EN_match_exponents ;

  // register sticky1
  assign sticky1_D_IN =
	     match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5 ?
	       x__h1072 :
	       x__h859 ;
  assign sticky1_EN =
	     EN_match_exponents &&
	     !match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3 ;

  // submodule rca
  assign rca_calculate_a = shifted_mantissa_1 ;
  assign rca_calculate_b = shifted_mantissa_2 ;

  // submodule rcs1
  assign rcs1_calculate_a = match_exponents_num1[30:23] ;
  assign rcs1_calculate_b = match_exponents_num2[30:23] ;

  // submodule rcs2
  assign rcs2_calculate_a = match_exponents_num2[30:23] ;
  assign rcs2_calculate_b = match_exponents_num1[30:23] ;

  // remaining internal signals
  assign IF_guard1_3_OR_sticky1_4_5_OR_rca_calculate_sh_ETC___d60 =
	     (guard1 | sticky1 || rca_calculate[1]) ?
	       x__h1630 :
	       rca_calculate[23:1] ;
  assign i__h761 = rcs1_calculate[7:0] - 8'd1 ;
  assign i__h996 = rcs2_calculate[7:0] - 8'd1 ;
  assign match_exponents_num1_BITS_22_TO_0__q1 = match_exponents_num1[22:0] ;
  assign match_exponents_num1_BITS_30_TO_23_EQ_match_ex_ETC___d3 =
	     match_exponents_num1[30:23] == match_exponents_num2[30:23] ;
  assign match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5 =
	     match_exponents_num1[30:23] <= match_exponents_num2[30:23] ;
  assign match_exponents_num2_BITS_22_TO_0__q2 = match_exponents_num2[22:0] ;
  assign shifted_part__h1062 = sm2__h600 & y__h1102 ;
  assign shifted_part__h849 = sm2__h600 & y__h896 ;
  assign sm1__h599 = { 1'b1, match_exponents_num1[22:0] } ;
  assign sm2__h600 = { 1'b1, match_exponents_num2[22:0] } ;
  assign x__h1072 = shifted_part__h1062 != 24'd0 ;
  assign x__h1630 = rca_calculate[23:1] + 23'd1 ;
  assign x__h2055 = rca_calculate[22:0] + 23'd1 ;
  assign x__h741 = match_exponents_num2_BITS_22_TO_0__q2[i__h761[4:0]] ;
  assign x__h859 = shifted_part__h849 != 24'd0 ;
  assign x__h977 = match_exponents_num1_BITS_22_TO_0__q1[i__h996[4:0]] ;
  assign y__h1102 = 24'hFFFFFF >> y__h1104 ;
  assign y__h1104 = 8'd25 - rcs2_calculate[7:0] ;
  assign y__h896 = 24'hFFFFFF >> y__h898 ;
  assign y__h898 = 8'd25 - rcs1_calculate[7:0] ;
  assign y_avValue_fst__h1161 =
	     match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5 ?
	       rcs2_calculate[7:0] :
	       rcs1_calculate[7:0] ;
  assign y_avValue_snd_fst__h1200 =
	     match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5 ?
	       match_exponents_num2[30:23] :
	       match_exponents_num1[30:23] ;
  assign y_avValue_snd_snd_fst__h1205 =
	     match_exponents_num1_BITS_30_TO_23_ULE_match_e_ETC___d5 ?
	       y_avValue_snd_snd_fst__h1216 :
	       sm1__h599 ;
  assign y_avValue_snd_snd_fst__h1216 = sm1__h599 >> rcs2_calculate[7:0] ;
  assign y_avValue_snd_snd_snd__h1215 = sm2__h600 >> rcs1_calculate[7:0] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        diff_reg <= `BSV_ASSIGNMENT_DELAY 8'd0;
	done1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	done2 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	done3 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	final_mantissa <= `BSV_ASSIGNMENT_DELAY 23'd0;
	guard1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
	man_carry <= `BSV_ASSIGNMENT_DELAY 1'd0;
	new_exp <= `BSV_ASSIGNMENT_DELAY 8'd0;
	res <= `BSV_ASSIGNMENT_DELAY 32'd0;
	shifted_mantissa_1 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	shifted_mantissa_2 <= `BSV_ASSIGNMENT_DELAY 24'd0;
	sticky1 <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (diff_reg_EN) diff_reg <= `BSV_ASSIGNMENT_DELAY diff_reg_D_IN;
	if (done1_EN) done1 <= `BSV_ASSIGNMENT_DELAY done1_D_IN;
	if (done2_EN) done2 <= `BSV_ASSIGNMENT_DELAY done2_D_IN;
	if (done3_EN) done3 <= `BSV_ASSIGNMENT_DELAY done3_D_IN;
	if (final_mantissa_EN)
	  final_mantissa <= `BSV_ASSIGNMENT_DELAY final_mantissa_D_IN;
	if (guard1_EN) guard1 <= `BSV_ASSIGNMENT_DELAY guard1_D_IN;
	if (man_carry_EN) man_carry <= `BSV_ASSIGNMENT_DELAY man_carry_D_IN;
	if (new_exp_EN) new_exp <= `BSV_ASSIGNMENT_DELAY new_exp_D_IN;
	if (res_EN) res <= `BSV_ASSIGNMENT_DELAY res_D_IN;
	if (shifted_mantissa_1_EN)
	  shifted_mantissa_1 <= `BSV_ASSIGNMENT_DELAY shifted_mantissa_1_D_IN;
	if (shifted_mantissa_2_EN)
	  shifted_mantissa_2 <= `BSV_ASSIGNMENT_DELAY shifted_mantissa_2_D_IN;
	if (sticky1_EN) sticky1 <= `BSV_ASSIGNMENT_DELAY sticky1_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    diff_reg = 8'hAA;
    done1 = 1'h0;
    done2 = 1'h0;
    done3 = 1'h0;
    final_mantissa = 23'h2AAAAA;
    guard1 = 1'h0;
    man_carry = 1'h0;
    new_exp = 8'hAA;
    res = 32'hAAAAAAAA;
    shifted_mantissa_1 = 24'hAAAAAA;
    shifted_mantissa_2 = 24'hAAAAAA;
    sticky1 = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFP32_Adder

