//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Fri Nov  7 13:23:28 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// calculate                      O     9
// RDY_calculate                  O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// calculate_a                    I     8
// calculate_b                    I     8
//
// Combinational paths from inputs to outputs:
//   (calculate_a, calculate_b) -> calculate
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRippleCarrySubtractor(CLK,
			       RST_N,

			       calculate_a,
			       calculate_b,
			       calculate,
			       RDY_calculate);
  input  CLK;
  input  RST_N;

  // value method calculate
  input  [7 : 0] calculate_a;
  input  [7 : 0] calculate_b;
  output [8 : 0] calculate;
  output RDY_calculate;

  // signals for module outputs
  wire [8 : 0] calculate;
  wire RDY_calculate;

  // remaining internal signals
  wire [8 : 0] IF_x03_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1;
  wire [6 : 0] calculate_a_BIT_6_XOR_calculate_b_BIT_6_8_XOR__ETC___d73;
  wire [4 : 0] calculate_a_BIT_4_3_XOR_calculate_b_BIT_4_5_2__ETC___d72;
  wire [2 : 0] calculate_a_BIT_2_1_XOR_calculate_b_BIT_2_3_6__ETC___d71;
  wire x__h1060,
       x__h1106,
       x__h1129,
       x__h1212,
       x__h1258,
       x__h1281,
       x__h1364,
       x__h1410,
       x__h1433,
       x__h1637,
       x__h1713,
       x__h1789,
       x__h1865,
       x__h1941,
       x__h2017,
       x__h2093,
       x__h303,
       x__h451,
       x__h521,
       x__h604,
       x__h650,
       x__h673,
       x__h756,
       x__h802,
       x__h825,
       x__h908,
       x__h954,
       x__h977,
       y__h1061,
       y__h1107,
       y__h1213,
       y__h1259,
       y__h1365,
       y__h1411,
       y__h452,
       y__h498,
       y__h605,
       y__h651,
       y__h757,
       y__h803,
       y__h909,
       y__h955;

  // value method calculate
  assign calculate =
	     { x__h1364 | y__h1365,
	       x__h1637 ^ x__h1410,
	       calculate_a_BIT_6_XOR_calculate_b_BIT_6_8_XOR__ETC___d73 } ;
  assign RDY_calculate = 1'd1 ;

  // remaining internal signals
  assign IF_x03_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1 =
	     (x__h303 & calculate_b[0]) ? 9'd2 : 9'd0 ;
  assign calculate_a_BIT_2_1_XOR_calculate_b_BIT_2_3_6__ETC___d71 =
	     { x__h2017 ^ x__h650,
	       x__h2093 ^ IF_x03_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1[1],
	       calculate_a[0] ^ calculate_b[0] } ;
  assign calculate_a_BIT_4_3_XOR_calculate_b_BIT_4_5_2__ETC___d72 =
	     { x__h1865 ^ x__h954,
	       x__h1941 ^ x__h802,
	       calculate_a_BIT_2_1_XOR_calculate_b_BIT_2_3_6__ETC___d71 } ;
  assign calculate_a_BIT_6_XOR_calculate_b_BIT_6_8_XOR__ETC___d73 =
	     { x__h1713 ^ x__h1258,
	       x__h1789 ^ x__h1106,
	       calculate_a_BIT_4_3_XOR_calculate_b_BIT_4_5_2__ETC___d72 } ;
  assign x__h1060 = x__h1129 & calculate_b[5] ;
  assign x__h1106 = x__h908 | y__h909 ;
  assign x__h1129 = ~calculate_a[5] ;
  assign x__h1212 = x__h1281 & calculate_b[6] ;
  assign x__h1258 = x__h1060 | y__h1061 ;
  assign x__h1281 = ~calculate_a[6] ;
  assign x__h1364 = x__h1433 & calculate_b[7] ;
  assign x__h1410 = x__h1212 | y__h1213 ;
  assign x__h1433 = ~calculate_a[7] ;
  assign x__h1637 = calculate_a[7] ^ calculate_b[7] ;
  assign x__h1713 = calculate_a[6] ^ calculate_b[6] ;
  assign x__h1789 = calculate_a[5] ^ calculate_b[5] ;
  assign x__h1865 = calculate_a[4] ^ calculate_b[4] ;
  assign x__h1941 = calculate_a[3] ^ calculate_b[3] ;
  assign x__h2017 = calculate_a[2] ^ calculate_b[2] ;
  assign x__h2093 = calculate_a[1] ^ calculate_b[1] ;
  assign x__h303 = ~calculate_a[0] ;
  assign x__h451 = x__h521 & calculate_b[1] ;
  assign x__h521 = ~calculate_a[1] ;
  assign x__h604 = x__h673 & calculate_b[2] ;
  assign x__h650 = x__h451 | y__h452 ;
  assign x__h673 = ~calculate_a[2] ;
  assign x__h756 = x__h825 & calculate_b[3] ;
  assign x__h802 = x__h604 | y__h605 ;
  assign x__h825 = ~calculate_a[3] ;
  assign x__h908 = x__h977 & calculate_b[4] ;
  assign x__h954 = x__h756 | y__h757 ;
  assign x__h977 = ~calculate_a[4] ;
  assign y__h1061 = x__h1106 & y__h1107 ;
  assign y__h1107 = x__h1129 ^ calculate_b[5] ;
  assign y__h1213 = x__h1258 & y__h1259 ;
  assign y__h1259 = x__h1281 ^ calculate_b[6] ;
  assign y__h1365 = x__h1410 & y__h1411 ;
  assign y__h1411 = x__h1433 ^ calculate_b[7] ;
  assign y__h452 =
	     IF_x03_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1[1] & y__h498 ;
  assign y__h498 = x__h521 ^ calculate_b[1] ;
  assign y__h605 = x__h650 & y__h651 ;
  assign y__h651 = x__h673 ^ calculate_b[2] ;
  assign y__h757 = x__h802 & y__h803 ;
  assign y__h803 = x__h825 ^ calculate_b[3] ;
  assign y__h909 = x__h954 & y__h955 ;
  assign y__h955 = x__h977 ^ calculate_b[4] ;
endmodule  // mkRippleCarrySubtractor

