//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Fri Nov  7 13:23:28 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// calculate                      O    25
// RDY_calculate                  O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// calculate_a                    I    24
// calculate_b                    I    24
//
// Combinational paths from inputs to outputs:
//   (calculate_a, calculate_b) -> calculate
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRippleCarryAdder(CLK,
			  RST_N,

			  calculate_a,
			  calculate_b,
			  calculate,
			  RDY_calculate);
  input  CLK;
  input  RST_N;

  // value method calculate
  input  [23 : 0] calculate_a;
  input  [23 : 0] calculate_b;
  output [24 : 0] calculate;
  output RDY_calculate;

  // signals for module outputs
  wire [24 : 0] calculate;
  wire RDY_calculate;

  // remaining internal signals
  wire [24 : 0] IF_calculate_a_BIT_0_AND_calculate_b_BIT_0_THE_ETC__q1;
  wire [22 : 0] calculate_a_BIT_22_XOR_calculate_b_BIT_22_38_X_ETC___d178;
  wire [20 : 0] calculate_a_BIT_20_0_XOR_calculate_b_BIT_20_1__ETC___d177;
  wire [18 : 0] calculate_a_BIT_18_6_XOR_calculate_b_BIT_18_7__ETC___d176;
  wire [16 : 0] calculate_a_BIT_16_2_XOR_calculate_b_BIT_16_3__ETC___d175;
  wire [14 : 0] calculate_a_BIT_14_8_XOR_calculate_b_BIT_14_9__ETC___d174;
  wire [12 : 0] calculate_a_BIT_12_4_XOR_calculate_b_BIT_12_5__ETC___d173;
  wire [10 : 0] calculate_a_BIT_10_0_XOR_calculate_b_BIT_10_1__ETC___d172;
  wire [8 : 0] calculate_a_BIT_8_6_XOR_calculate_b_BIT_8_7_6__ETC___d171;
  wire [6 : 0] calculate_a_BIT_6_2_XOR_calculate_b_BIT_6_3_0__ETC___d170;
  wire [4 : 0] calculate_a_BIT_4_8_XOR_calculate_b_BIT_4_9_4__ETC___d169;
  wire [2 : 0] calculate_a_BIT_2_4_XOR_calculate_b_BIT_2_5_8__ETC___d168;
  wire x__h1012,
       x__h1117,
       x__h1162,
       x__h1267,
       x__h1312,
       x__h1417,
       x__h1462,
       x__h1567,
       x__h1612,
       x__h1717,
       x__h1762,
       x__h1867,
       x__h1912,
       x__h2017,
       x__h2062,
       x__h2167,
       x__h2212,
       x__h2317,
       x__h2362,
       x__h2467,
       x__h2512,
       x__h2617,
       x__h2662,
       x__h2767,
       x__h2812,
       x__h2917,
       x__h2962,
       x__h3067,
       x__h3112,
       x__h3217,
       x__h3262,
       x__h3367,
       x__h3412,
       x__h3517,
       x__h3562,
       x__h3667,
       x__h3712,
       x__h3817,
       x__h3862,
       x__h3967,
       x__h4012,
       x__h4117,
       x__h4162,
       x__h4628,
       x__h4704,
       x__h4780,
       x__h4856,
       x__h4932,
       x__h5008,
       x__h5084,
       x__h5160,
       x__h5236,
       x__h5312,
       x__h5388,
       x__h5464,
       x__h5540,
       x__h5616,
       x__h5692,
       x__h5768,
       x__h5844,
       x__h5920,
       x__h5996,
       x__h6072,
       x__h6148,
       x__h6224,
       x__h6300,
       x__h816,
       x__h967,
       y__h1118,
       y__h1268,
       y__h1418,
       y__h1568,
       y__h1718,
       y__h1868,
       y__h2018,
       y__h2168,
       y__h2318,
       y__h2468,
       y__h2618,
       y__h2768,
       y__h2918,
       y__h3068,
       y__h3218,
       y__h3368,
       y__h3518,
       y__h3668,
       y__h3818,
       y__h3968,
       y__h4118,
       y__h817,
       y__h968;

  // value method calculate
  assign calculate =
	     { x__h4117 | y__h4118,
	       x__h4628 ^ x__h4162,
	       calculate_a_BIT_22_XOR_calculate_b_BIT_22_38_X_ETC___d178 } ;
  assign RDY_calculate = 1'd1 ;

  // remaining internal signals
  assign IF_calculate_a_BIT_0_AND_calculate_b_BIT_0_THE_ETC__q1 =
	     (calculate_a[0] & calculate_b[0]) ? 25'd2 : 25'd0 ;
  assign calculate_a_BIT_10_0_XOR_calculate_b_BIT_10_1__ETC___d172 =
	     { x__h5616 ^ x__h2212,
	       x__h5692 ^ x__h2062,
	       calculate_a_BIT_8_6_XOR_calculate_b_BIT_8_7_6__ETC___d171 } ;
  assign calculate_a_BIT_12_4_XOR_calculate_b_BIT_12_5__ETC___d173 =
	     { x__h5464 ^ x__h2512,
	       x__h5540 ^ x__h2362,
	       calculate_a_BIT_10_0_XOR_calculate_b_BIT_10_1__ETC___d172 } ;
  assign calculate_a_BIT_14_8_XOR_calculate_b_BIT_14_9__ETC___d174 =
	     { x__h5312 ^ x__h2812,
	       x__h5388 ^ x__h2662,
	       calculate_a_BIT_12_4_XOR_calculate_b_BIT_12_5__ETC___d173 } ;
  assign calculate_a_BIT_16_2_XOR_calculate_b_BIT_16_3__ETC___d175 =
	     { x__h5160 ^ x__h3112,
	       x__h5236 ^ x__h2962,
	       calculate_a_BIT_14_8_XOR_calculate_b_BIT_14_9__ETC___d174 } ;
  assign calculate_a_BIT_18_6_XOR_calculate_b_BIT_18_7__ETC___d176 =
	     { x__h5008 ^ x__h3412,
	       x__h5084 ^ x__h3262,
	       calculate_a_BIT_16_2_XOR_calculate_b_BIT_16_3__ETC___d175 } ;
  assign calculate_a_BIT_20_0_XOR_calculate_b_BIT_20_1__ETC___d177 =
	     { x__h4856 ^ x__h3712,
	       x__h4932 ^ x__h3562,
	       calculate_a_BIT_18_6_XOR_calculate_b_BIT_18_7__ETC___d176 } ;
  assign calculate_a_BIT_22_XOR_calculate_b_BIT_22_38_X_ETC___d178 =
	     { x__h4704 ^ x__h4012,
	       x__h4780 ^ x__h3862,
	       calculate_a_BIT_20_0_XOR_calculate_b_BIT_20_1__ETC___d177 } ;
  assign calculate_a_BIT_2_4_XOR_calculate_b_BIT_2_5_8__ETC___d168 =
	     { x__h6224 ^ x__h1012,
	       x__h6300 ^
	       IF_calculate_a_BIT_0_AND_calculate_b_BIT_0_THE_ETC__q1[1],
	       calculate_a[0] ^ calculate_b[0] } ;
  assign calculate_a_BIT_4_8_XOR_calculate_b_BIT_4_9_4__ETC___d169 =
	     { x__h6072 ^ x__h1312,
	       x__h6148 ^ x__h1162,
	       calculate_a_BIT_2_4_XOR_calculate_b_BIT_2_5_8__ETC___d168 } ;
  assign calculate_a_BIT_6_2_XOR_calculate_b_BIT_6_3_0__ETC___d170 =
	     { x__h5920 ^ x__h1612,
	       x__h5996 ^ x__h1462,
	       calculate_a_BIT_4_8_XOR_calculate_b_BIT_4_9_4__ETC___d169 } ;
  assign calculate_a_BIT_8_6_XOR_calculate_b_BIT_8_7_6__ETC___d171 =
	     { x__h5768 ^ x__h1912,
	       x__h5844 ^ x__h1762,
	       calculate_a_BIT_6_2_XOR_calculate_b_BIT_6_3_0__ETC___d170 } ;
  assign x__h1012 = x__h816 | y__h817 ;
  assign x__h1117 = calculate_a[3] & calculate_b[3] ;
  assign x__h1162 = x__h967 | y__h968 ;
  assign x__h1267 = calculate_a[4] & calculate_b[4] ;
  assign x__h1312 = x__h1117 | y__h1118 ;
  assign x__h1417 = calculate_a[5] & calculate_b[5] ;
  assign x__h1462 = x__h1267 | y__h1268 ;
  assign x__h1567 = calculate_a[6] & calculate_b[6] ;
  assign x__h1612 = x__h1417 | y__h1418 ;
  assign x__h1717 = calculate_a[7] & calculate_b[7] ;
  assign x__h1762 = x__h1567 | y__h1568 ;
  assign x__h1867 = calculate_a[8] & calculate_b[8] ;
  assign x__h1912 = x__h1717 | y__h1718 ;
  assign x__h2017 = calculate_a[9] & calculate_b[9] ;
  assign x__h2062 = x__h1867 | y__h1868 ;
  assign x__h2167 = calculate_a[10] & calculate_b[10] ;
  assign x__h2212 = x__h2017 | y__h2018 ;
  assign x__h2317 = calculate_a[11] & calculate_b[11] ;
  assign x__h2362 = x__h2167 | y__h2168 ;
  assign x__h2467 = calculate_a[12] & calculate_b[12] ;
  assign x__h2512 = x__h2317 | y__h2318 ;
  assign x__h2617 = calculate_a[13] & calculate_b[13] ;
  assign x__h2662 = x__h2467 | y__h2468 ;
  assign x__h2767 = calculate_a[14] & calculate_b[14] ;
  assign x__h2812 = x__h2617 | y__h2618 ;
  assign x__h2917 = calculate_a[15] & calculate_b[15] ;
  assign x__h2962 = x__h2767 | y__h2768 ;
  assign x__h3067 = calculate_a[16] & calculate_b[16] ;
  assign x__h3112 = x__h2917 | y__h2918 ;
  assign x__h3217 = calculate_a[17] & calculate_b[17] ;
  assign x__h3262 = x__h3067 | y__h3068 ;
  assign x__h3367 = calculate_a[18] & calculate_b[18] ;
  assign x__h3412 = x__h3217 | y__h3218 ;
  assign x__h3517 = calculate_a[19] & calculate_b[19] ;
  assign x__h3562 = x__h3367 | y__h3368 ;
  assign x__h3667 = calculate_a[20] & calculate_b[20] ;
  assign x__h3712 = x__h3517 | y__h3518 ;
  assign x__h3817 = calculate_a[21] & calculate_b[21] ;
  assign x__h3862 = x__h3667 | y__h3668 ;
  assign x__h3967 = calculate_a[22] & calculate_b[22] ;
  assign x__h4012 = x__h3817 | y__h3818 ;
  assign x__h4117 = calculate_a[23] & calculate_b[23] ;
  assign x__h4162 = x__h3967 | y__h3968 ;
  assign x__h4628 = calculate_a[23] ^ calculate_b[23] ;
  assign x__h4704 = calculate_a[22] ^ calculate_b[22] ;
  assign x__h4780 = calculate_a[21] ^ calculate_b[21] ;
  assign x__h4856 = calculate_a[20] ^ calculate_b[20] ;
  assign x__h4932 = calculate_a[19] ^ calculate_b[19] ;
  assign x__h5008 = calculate_a[18] ^ calculate_b[18] ;
  assign x__h5084 = calculate_a[17] ^ calculate_b[17] ;
  assign x__h5160 = calculate_a[16] ^ calculate_b[16] ;
  assign x__h5236 = calculate_a[15] ^ calculate_b[15] ;
  assign x__h5312 = calculate_a[14] ^ calculate_b[14] ;
  assign x__h5388 = calculate_a[13] ^ calculate_b[13] ;
  assign x__h5464 = calculate_a[12] ^ calculate_b[12] ;
  assign x__h5540 = calculate_a[11] ^ calculate_b[11] ;
  assign x__h5616 = calculate_a[10] ^ calculate_b[10] ;
  assign x__h5692 = calculate_a[9] ^ calculate_b[9] ;
  assign x__h5768 = calculate_a[8] ^ calculate_b[8] ;
  assign x__h5844 = calculate_a[7] ^ calculate_b[7] ;
  assign x__h5920 = calculate_a[6] ^ calculate_b[6] ;
  assign x__h5996 = calculate_a[5] ^ calculate_b[5] ;
  assign x__h6072 = calculate_a[4] ^ calculate_b[4] ;
  assign x__h6148 = calculate_a[3] ^ calculate_b[3] ;
  assign x__h6224 = calculate_a[2] ^ calculate_b[2] ;
  assign x__h6300 = calculate_a[1] ^ calculate_b[1] ;
  assign x__h816 = calculate_a[1] & calculate_b[1] ;
  assign x__h967 = calculate_a[2] & calculate_b[2] ;
  assign y__h1118 = x__h1162 & x__h6148 ;
  assign y__h1268 = x__h1312 & x__h6072 ;
  assign y__h1418 = x__h1462 & x__h5996 ;
  assign y__h1568 = x__h1612 & x__h5920 ;
  assign y__h1718 = x__h1762 & x__h5844 ;
  assign y__h1868 = x__h1912 & x__h5768 ;
  assign y__h2018 = x__h2062 & x__h5692 ;
  assign y__h2168 = x__h2212 & x__h5616 ;
  assign y__h2318 = x__h2362 & x__h5540 ;
  assign y__h2468 = x__h2512 & x__h5464 ;
  assign y__h2618 = x__h2662 & x__h5388 ;
  assign y__h2768 = x__h2812 & x__h5312 ;
  assign y__h2918 = x__h2962 & x__h5236 ;
  assign y__h3068 = x__h3112 & x__h5160 ;
  assign y__h3218 = x__h3262 & x__h5084 ;
  assign y__h3368 = x__h3412 & x__h5008 ;
  assign y__h3518 = x__h3562 & x__h4932 ;
  assign y__h3668 = x__h3712 & x__h4856 ;
  assign y__h3818 = x__h3862 & x__h4780 ;
  assign y__h3968 = x__h4012 & x__h4704 ;
  assign y__h4118 = x__h4162 & x__h4628 ;
  assign y__h817 =
	     IF_calculate_a_BIT_0_AND_calculate_b_BIT_0_THE_ETC__q1[1] &
	     x__h6300 ;
  assign y__h968 = x__h1012 & x__h6224 ;
endmodule  // mkRippleCarryAdder

