//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Thu Nov  6 00:21:55 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// calculate                      O     9
// RDY_calculate                  O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// calculate_a                    I     8
// calculate_b                    I     8
//
// Combinational paths from inputs to outputs:
//   (calculate_a, calculate_b) -> calculate
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRippleCarrySubtractor(CLK,
			       RST_N,

			       calculate_a,
			       calculate_b,
			       calculate,
			       RDY_calculate);
  input  CLK;
  input  RST_N;

  // value method calculate
  input  [7 : 0] calculate_a;
  input  [7 : 0] calculate_b;
  output [8 : 0] calculate;
  output RDY_calculate;

  // signals for module outputs
  wire [8 : 0] calculate;
  wire RDY_calculate;

  // remaining internal signals
  wire [8 : 0] IF_x02_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1;
  wire [6 : 0] calculate_a_BIT_6_XOR_calculate_b_BIT_6_8_XOR__ETC___d73;
  wire [4 : 0] calculate_a_BIT_4_3_XOR_calculate_b_BIT_4_5_2__ETC___d72;
  wire [2 : 0] calculate_a_BIT_2_1_XOR_calculate_b_BIT_2_3_6__ETC___d71;
  wire x__h1059,
       x__h1105,
       x__h1128,
       x__h1211,
       x__h1257,
       x__h1280,
       x__h1363,
       x__h1409,
       x__h1432,
       x__h1636,
       x__h1712,
       x__h1788,
       x__h1864,
       x__h1940,
       x__h2016,
       x__h2092,
       x__h302,
       x__h450,
       x__h520,
       x__h603,
       x__h649,
       x__h672,
       x__h755,
       x__h801,
       x__h824,
       x__h907,
       x__h953,
       x__h976,
       y__h1060,
       y__h1106,
       y__h1212,
       y__h1258,
       y__h1364,
       y__h1410,
       y__h451,
       y__h497,
       y__h604,
       y__h650,
       y__h756,
       y__h802,
       y__h908,
       y__h954;

  // value method calculate
  assign calculate =
	     { x__h1363 | y__h1364,
	       x__h1636 ^ x__h1409,
	       calculate_a_BIT_6_XOR_calculate_b_BIT_6_8_XOR__ETC___d73 } ;
  assign RDY_calculate = 1'd1 ;

  // remaining internal signals
  assign IF_x02_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1 =
	     (x__h302 & calculate_b[0]) ? 9'd2 : 9'd0 ;
  assign calculate_a_BIT_2_1_XOR_calculate_b_BIT_2_3_6__ETC___d71 =
	     { x__h2016 ^ x__h649,
	       x__h2092 ^ IF_x02_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1[1],
	       calculate_a[0] ^ calculate_b[0] } ;
  assign calculate_a_BIT_4_3_XOR_calculate_b_BIT_4_5_2__ETC___d72 =
	     { x__h1864 ^ x__h953,
	       x__h1940 ^ x__h801,
	       calculate_a_BIT_2_1_XOR_calculate_b_BIT_2_3_6__ETC___d71 } ;
  assign calculate_a_BIT_6_XOR_calculate_b_BIT_6_8_XOR__ETC___d73 =
	     { x__h1712 ^ x__h1257,
	       x__h1788 ^ x__h1105,
	       calculate_a_BIT_4_3_XOR_calculate_b_BIT_4_5_2__ETC___d72 } ;
  assign x__h1059 = x__h1128 & calculate_b[5] ;
  assign x__h1105 = x__h907 | y__h908 ;
  assign x__h1128 = ~calculate_a[5] ;
  assign x__h1211 = x__h1280 & calculate_b[6] ;
  assign x__h1257 = x__h1059 | y__h1060 ;
  assign x__h1280 = ~calculate_a[6] ;
  assign x__h1363 = x__h1432 & calculate_b[7] ;
  assign x__h1409 = x__h1211 | y__h1212 ;
  assign x__h1432 = ~calculate_a[7] ;
  assign x__h1636 = calculate_a[7] ^ calculate_b[7] ;
  assign x__h1712 = calculate_a[6] ^ calculate_b[6] ;
  assign x__h1788 = calculate_a[5] ^ calculate_b[5] ;
  assign x__h1864 = calculate_a[4] ^ calculate_b[4] ;
  assign x__h1940 = calculate_a[3] ^ calculate_b[3] ;
  assign x__h2016 = calculate_a[2] ^ calculate_b[2] ;
  assign x__h2092 = calculate_a[1] ^ calculate_b[1] ;
  assign x__h302 = ~calculate_a[0] ;
  assign x__h450 = x__h520 & calculate_b[1] ;
  assign x__h520 = ~calculate_a[1] ;
  assign x__h603 = x__h672 & calculate_b[2] ;
  assign x__h649 = x__h450 | y__h451 ;
  assign x__h672 = ~calculate_a[2] ;
  assign x__h755 = x__h824 & calculate_b[3] ;
  assign x__h801 = x__h603 | y__h604 ;
  assign x__h824 = ~calculate_a[3] ;
  assign x__h907 = x__h976 & calculate_b[4] ;
  assign x__h953 = x__h755 | y__h756 ;
  assign x__h976 = ~calculate_a[4] ;
  assign y__h1060 = x__h1105 & y__h1106 ;
  assign y__h1106 = x__h1128 ^ calculate_b[5] ;
  assign y__h1212 = x__h1257 & y__h1258 ;
  assign y__h1258 = x__h1280 ^ calculate_b[6] ;
  assign y__h1364 = x__h1409 & y__h1410 ;
  assign y__h1410 = x__h1432 ^ calculate_b[7] ;
  assign y__h451 =
	     IF_x02_AND_calculate_b_BIT_0_THEN_2_ELSE_0__q1[1] & y__h497 ;
  assign y__h497 = x__h520 ^ calculate_b[1] ;
  assign y__h604 = x__h649 & y__h650 ;
  assign y__h650 = x__h672 ^ calculate_b[2] ;
  assign y__h756 = x__h801 & y__h802 ;
  assign y__h802 = x__h824 ^ calculate_b[3] ;
  assign y__h908 = x__h953 & y__h954 ;
  assign y__h954 = x__h976 ^ calculate_b[4] ;
endmodule  // mkRippleCarrySubtractor

