//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sat Nov  8 04:56:22 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// get_n_and_m_loaded             O     1 reg
// RDY_get_n_and_m_loaded         O     1 const
// RDY_n_and_m_load               O     1 const
// read_outcome_idx               O    10 reg
// RDY_read_outcome_idx           O     1 const
// RDY_send_transition_data       O     1 const
// RDY_send_emission_data         O     1 const
// RDY_send_outcome_data          O     1 const
// get_read_transition            O     1 reg
// RDY_get_read_transition        O     1 const
// RDY_set_read_transition        O     1 const
// get_read_emission              O     1 reg
// RDY_get_read_emission          O     1 const
// get_read_outcome               O     1 reg
// RDY_get_read_outcome           O     1 const
// get_reset_decoder              O     1 reg
// RDY_get_reset_decoder          O     1 const
// get_print_state                O     2 reg
// RDY_get_print_state            O     1 const
// get_num_obs                    O     6
// RDY_get_num_obs                O     1 const
// get_probab                     O    32 reg
// RDY_get_probab                 O     1 const
// get_init_done_flag             O     1 reg
// RDY_get_init_done_flag         O     1 const
// get_i_ctr                      O     5 reg
// RDY_get_i_ctr                  O     1 const
// get_j_ctr                      O     5 reg
// RDY_get_j_ctr                  O     1 const
// get_outcome                    O    32 reg
// RDY_get_outcome                O     1 const
// get_write_to_bt_flag           O     1 reg
// RDY_get_write_to_bt_flag       O     1 const
// get_max_stage_reg              O     5 reg
// RDY_get_max_stage_reg          O     1 const
// get_read_bt                    O     1 reg
// RDY_get_read_bt                O     1 const
// get_bt_t_ctr                   O    10 reg
// RDY_get_bt_t_ctr               O     1 const
// RDY_send_bt_data               O     1 const
// get_path_buffer                O     5 reg
// RDY_get_path_buffer            O     1 const
// get_path_ready                 O     1 reg
// RDY_get_path_ready             O     1 const
// get_curr_buffer                O    32 reg
// RDY_get_curr_buffer            O     1 const
// get_write_to_curr_flag         O     1 reg
// RDY_get_write_to_curr_flag     O     1 const
// get_read_curr                  O     1 reg
// RDY_get_read_curr              O     1 const
// get_read_prev                  O     1 reg
// RDY_get_read_prev              O     1 const
// RDY_send_prev_data             O     1 const
// RDY_send_curr_data             O     1 const
// get_switch_prev_curr           O     1 reg
// RDY_get_switch_prev_curr       O     1 const
// get_write_to_prev_flag         O     1 reg
// RDY_get_write_to_prev_flag     O     1 const
// get_prev_buffer                O    32 reg
// RDY_get_prev_buffer            O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// n_and_m_load_n                 I     5 reg
// n_and_m_load_m                 I     5 reg
// send_transition_data_data      I    32 reg
// send_emission_data_data        I    32 reg
// send_outcome_data_data         I    32 reg
// set_read_transition_val        I     1
// send_bt_data_data              I     5 reg
// send_prev_data_data            I    32
// send_curr_data_data            I    32
// EN_n_and_m_load                I     1
// EN_send_transition_data        I     1
// EN_send_emission_data          I     1
// EN_send_outcome_data           I     1
// EN_set_read_transition         I     1
// EN_send_bt_data                I     1
// EN_send_prev_data              I     1
// EN_send_curr_data              I     1
// EN_get_n_and_m_loaded          I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkViterbi(CLK,
		 RST_N,

		 EN_get_n_and_m_loaded,
		 get_n_and_m_loaded,
		 RDY_get_n_and_m_loaded,

		 n_and_m_load_n,
		 n_and_m_load_m,
		 EN_n_and_m_load,
		 RDY_n_and_m_load,

		 read_outcome_idx,
		 RDY_read_outcome_idx,

		 send_transition_data_data,
		 EN_send_transition_data,
		 RDY_send_transition_data,

		 send_emission_data_data,
		 EN_send_emission_data,
		 RDY_send_emission_data,

		 send_outcome_data_data,
		 EN_send_outcome_data,
		 RDY_send_outcome_data,

		 get_read_transition,
		 RDY_get_read_transition,

		 set_read_transition_val,
		 EN_set_read_transition,
		 RDY_set_read_transition,

		 get_read_emission,
		 RDY_get_read_emission,

		 get_read_outcome,
		 RDY_get_read_outcome,

		 get_reset_decoder,
		 RDY_get_reset_decoder,

		 get_print_state,
		 RDY_get_print_state,

		 get_num_obs,
		 RDY_get_num_obs,

		 get_probab,
		 RDY_get_probab,

		 get_init_done_flag,
		 RDY_get_init_done_flag,

		 get_i_ctr,
		 RDY_get_i_ctr,

		 get_j_ctr,
		 RDY_get_j_ctr,

		 get_outcome,
		 RDY_get_outcome,

		 get_write_to_bt_flag,
		 RDY_get_write_to_bt_flag,

		 get_max_stage_reg,
		 RDY_get_max_stage_reg,

		 get_read_bt,
		 RDY_get_read_bt,

		 get_bt_t_ctr,
		 RDY_get_bt_t_ctr,

		 send_bt_data_data,
		 EN_send_bt_data,
		 RDY_send_bt_data,

		 get_path_buffer,
		 RDY_get_path_buffer,

		 get_path_ready,
		 RDY_get_path_ready,

		 get_curr_buffer,
		 RDY_get_curr_buffer,

		 get_write_to_curr_flag,
		 RDY_get_write_to_curr_flag,

		 get_read_curr,
		 RDY_get_read_curr,

		 get_read_prev,
		 RDY_get_read_prev,

		 send_prev_data_data,
		 EN_send_prev_data,
		 RDY_send_prev_data,

		 send_curr_data_data,
		 EN_send_curr_data,
		 RDY_send_curr_data,

		 get_switch_prev_curr,
		 RDY_get_switch_prev_curr,

		 get_write_to_prev_flag,
		 RDY_get_write_to_prev_flag,

		 get_prev_buffer,
		 RDY_get_prev_buffer);
  input  CLK;
  input  RST_N;

  // actionvalue method get_n_and_m_loaded
  input  EN_get_n_and_m_loaded;
  output get_n_and_m_loaded;
  output RDY_get_n_and_m_loaded;

  // action method n_and_m_load
  input  [4 : 0] n_and_m_load_n;
  input  [4 : 0] n_and_m_load_m;
  input  EN_n_and_m_load;
  output RDY_n_and_m_load;

  // value method read_outcome_idx
  output [9 : 0] read_outcome_idx;
  output RDY_read_outcome_idx;

  // action method send_transition_data
  input  [31 : 0] send_transition_data_data;
  input  EN_send_transition_data;
  output RDY_send_transition_data;

  // action method send_emission_data
  input  [31 : 0] send_emission_data_data;
  input  EN_send_emission_data;
  output RDY_send_emission_data;

  // action method send_outcome_data
  input  [31 : 0] send_outcome_data_data;
  input  EN_send_outcome_data;
  output RDY_send_outcome_data;

  // value method get_read_transition
  output get_read_transition;
  output RDY_get_read_transition;

  // action method set_read_transition
  input  set_read_transition_val;
  input  EN_set_read_transition;
  output RDY_set_read_transition;

  // value method get_read_emission
  output get_read_emission;
  output RDY_get_read_emission;

  // value method get_read_outcome
  output get_read_outcome;
  output RDY_get_read_outcome;

  // value method get_reset_decoder
  output get_reset_decoder;
  output RDY_get_reset_decoder;

  // value method get_print_state
  output [1 : 0] get_print_state;
  output RDY_get_print_state;

  // value method get_num_obs
  output [5 : 0] get_num_obs;
  output RDY_get_num_obs;

  // value method get_probab
  output [31 : 0] get_probab;
  output RDY_get_probab;

  // value method get_init_done_flag
  output get_init_done_flag;
  output RDY_get_init_done_flag;

  // value method get_i_ctr
  output [4 : 0] get_i_ctr;
  output RDY_get_i_ctr;

  // value method get_j_ctr
  output [4 : 0] get_j_ctr;
  output RDY_get_j_ctr;

  // value method get_outcome
  output [31 : 0] get_outcome;
  output RDY_get_outcome;

  // value method get_write_to_bt_flag
  output get_write_to_bt_flag;
  output RDY_get_write_to_bt_flag;

  // value method get_max_stage_reg
  output [4 : 0] get_max_stage_reg;
  output RDY_get_max_stage_reg;

  // value method get_read_bt
  output get_read_bt;
  output RDY_get_read_bt;

  // value method get_bt_t_ctr
  output [9 : 0] get_bt_t_ctr;
  output RDY_get_bt_t_ctr;

  // action method send_bt_data
  input  [4 : 0] send_bt_data_data;
  input  EN_send_bt_data;
  output RDY_send_bt_data;

  // value method get_path_buffer
  output [4 : 0] get_path_buffer;
  output RDY_get_path_buffer;

  // value method get_path_ready
  output get_path_ready;
  output RDY_get_path_ready;

  // value method get_curr_buffer
  output [31 : 0] get_curr_buffer;
  output RDY_get_curr_buffer;

  // value method get_write_to_curr_flag
  output get_write_to_curr_flag;
  output RDY_get_write_to_curr_flag;

  // value method get_read_curr
  output get_read_curr;
  output RDY_get_read_curr;

  // value method get_read_prev
  output get_read_prev;
  output RDY_get_read_prev;

  // action method send_prev_data
  input  [31 : 0] send_prev_data_data;
  input  EN_send_prev_data;
  output RDY_send_prev_data;

  // action method send_curr_data
  input  [31 : 0] send_curr_data_data;
  input  EN_send_curr_data;
  output RDY_send_curr_data;

  // value method get_switch_prev_curr
  output get_switch_prev_curr;
  output RDY_get_switch_prev_curr;

  // value method get_write_to_prev_flag
  output get_write_to_prev_flag;
  output RDY_get_write_to_prev_flag;

  // value method get_prev_buffer
  output [31 : 0] get_prev_buffer;
  output RDY_get_prev_buffer;

  // signals for module outputs
  wire [31 : 0] get_curr_buffer, get_outcome, get_prev_buffer, get_probab;
  wire [9 : 0] get_bt_t_ctr, read_outcome_idx;
  wire [5 : 0] get_num_obs;
  wire [4 : 0] get_i_ctr, get_j_ctr, get_max_stage_reg, get_path_buffer;
  wire [1 : 0] get_print_state;
  wire RDY_get_bt_t_ctr,
       RDY_get_curr_buffer,
       RDY_get_i_ctr,
       RDY_get_init_done_flag,
       RDY_get_j_ctr,
       RDY_get_max_stage_reg,
       RDY_get_n_and_m_loaded,
       RDY_get_num_obs,
       RDY_get_outcome,
       RDY_get_path_buffer,
       RDY_get_path_ready,
       RDY_get_prev_buffer,
       RDY_get_print_state,
       RDY_get_probab,
       RDY_get_read_bt,
       RDY_get_read_curr,
       RDY_get_read_emission,
       RDY_get_read_outcome,
       RDY_get_read_prev,
       RDY_get_read_transition,
       RDY_get_reset_decoder,
       RDY_get_switch_prev_curr,
       RDY_get_write_to_bt_flag,
       RDY_get_write_to_curr_flag,
       RDY_get_write_to_prev_flag,
       RDY_n_and_m_load,
       RDY_read_outcome_idx,
       RDY_send_bt_data,
       RDY_send_curr_data,
       RDY_send_emission_data,
       RDY_send_outcome_data,
       RDY_send_prev_data,
       RDY_send_transition_data,
       RDY_set_read_transition,
       get_init_done_flag,
       get_n_and_m_loaded,
       get_path_ready,
       get_read_bt,
       get_read_curr,
       get_read_emission,
       get_read_outcome,
       get_read_prev,
       get_read_transition,
       get_reset_decoder,
       get_switch_prev_curr,
       get_write_to_bt_flag,
       get_write_to_curr_flag,
       get_write_to_prev_flag;

  // register bt_buffer
  reg [4 : 0] bt_buffer;
  wire [4 : 0] bt_buffer_D_IN;
  wire bt_buffer_EN;

  // register bt_max
  reg [31 : 0] bt_max;
  wire [31 : 0] bt_max_D_IN;
  wire bt_max_EN;

  // register bt_ready
  reg bt_ready;
  wire bt_ready_D_IN, bt_ready_EN;

  // register bt_t_ctr
  reg [9 : 0] bt_t_ctr;
  wire [9 : 0] bt_t_ctr_D_IN;
  wire bt_t_ctr_EN;

  // register curr_buffer
  reg [31 : 0] curr_buffer;
  wire [31 : 0] curr_buffer_D_IN;
  wire curr_buffer_EN;

  // register curr_ready
  reg curr_ready;
  wire curr_ready_D_IN, curr_ready_EN;

  // register emission_buffer
  reg [31 : 0] emission_buffer;
  wire [31 : 0] emission_buffer_D_IN;
  wire emission_buffer_EN;

  // register emission_ready
  reg emission_ready;
  wire emission_ready_D_IN, emission_ready_EN;

  // register i_ctr
  reg [4 : 0] i_ctr;
  reg [4 : 0] i_ctr_D_IN;
  wire i_ctr_EN;

  // register init_done_flag
  reg init_done_flag;
  wire init_done_flag_D_IN, init_done_flag_EN;

  // register init_state
  reg [1 : 0] init_state;
  wire [1 : 0] init_state_D_IN;
  wire init_state_EN;

  // register j_ctr
  reg [4 : 0] j_ctr;
  wire [4 : 0] j_ctr_D_IN;
  wire j_ctr_EN;

  // register loop_done_flag
  reg loop_done_flag;
  wire loop_done_flag_D_IN, loop_done_flag_EN;

  // register m_reg
  reg [4 : 0] m_reg;
  wire [4 : 0] m_reg_D_IN;
  wire m_reg_EN;

  // register machine_state
  reg [3 : 0] machine_state;
  wire [3 : 0] machine_state_D_IN;
  wire machine_state_EN;

  // register max_path
  reg [4 : 0] max_path;
  wire [4 : 0] max_path_D_IN;
  wire max_path_EN;

  // register max_reg
  reg [31 : 0] max_reg;
  wire [31 : 0] max_reg_D_IN;
  wire max_reg_EN;

  // register max_state_reg
  reg [4 : 0] max_state_reg;
  wire [4 : 0] max_state_reg_D_IN;
  wire max_state_reg_EN;

  // register n_and_m_loaded
  reg n_and_m_loaded;
  wire n_and_m_loaded_D_IN, n_and_m_loaded_EN;

  // register n_reg
  reg [4 : 0] n_reg;
  wire [4 : 0] n_reg_D_IN;
  wire n_reg_EN;

  // register outcome_buffer
  reg [31 : 0] outcome_buffer;
  wire [31 : 0] outcome_buffer_D_IN;
  wire outcome_buffer_EN;

  // register outcome_idx
  reg [9 : 0] outcome_idx;
  wire [9 : 0] outcome_idx_D_IN;
  wire outcome_idx_EN;

  // register outcome_ready
  reg outcome_ready;
  wire outcome_ready_D_IN, outcome_ready_EN;

  // register path_buffer
  reg [4 : 0] path_buffer;
  wire [4 : 0] path_buffer_D_IN;
  wire path_buffer_EN;

  // register path_ready
  reg path_ready;
  wire path_ready_D_IN, path_ready_EN;

  // register prev_buffer
  reg [31 : 0] prev_buffer;
  wire [31 : 0] prev_buffer_D_IN;
  wire prev_buffer_EN;

  // register prev_ready
  reg prev_ready;
  wire prev_ready_D_IN, prev_ready_EN;

  // register print_state
  reg [1 : 0] print_state;
  reg [1 : 0] print_state_D_IN;
  wire print_state_EN;

  // register read_bt
  reg read_bt;
  wire read_bt_D_IN, read_bt_EN;

  // register read_curr
  reg read_curr;
  wire read_curr_D_IN, read_curr_EN;

  // register read_emission
  reg read_emission;
  wire read_emission_D_IN, read_emission_EN;

  // register read_outcome
  reg read_outcome;
  wire read_outcome_D_IN, read_outcome_EN;

  // register read_prev
  reg read_prev;
  wire read_prev_D_IN, read_prev_EN;

  // register read_transition
  reg read_transition;
  reg read_transition_D_IN;
  wire read_transition_EN;

  // register reset_machine_flag
  reg reset_machine_flag;
  wire reset_machine_flag_D_IN, reset_machine_flag_EN;

  // register switch_prev_curr
  reg switch_prev_curr;
  wire switch_prev_curr_D_IN, switch_prev_curr_EN;

  // register t_ctr
  reg [9 : 0] t_ctr;
  reg [9 : 0] t_ctr_D_IN;
  wire t_ctr_EN;

  // register t_start
  reg [9 : 0] t_start;
  wire [9 : 0] t_start_D_IN;
  wire t_start_EN;

  // register transition_buffer
  reg [31 : 0] transition_buffer;
  wire [31 : 0] transition_buffer_D_IN;
  wire transition_buffer_EN;

  // register transition_ready
  reg transition_ready;
  wire transition_ready_D_IN, transition_ready_EN;

  // register write_to_bt_flag
  reg write_to_bt_flag;
  wire write_to_bt_flag_D_IN, write_to_bt_flag_EN;

  // register write_to_curr_flag
  reg write_to_curr_flag;
  wire write_to_curr_flag_D_IN, write_to_curr_flag_EN;

  // register write_to_prev_flag
  reg write_to_prev_flag;
  wire write_to_prev_flag_D_IN, write_to_prev_flag_EN;

  // ports of submodule adder
  wire [31 : 0] adder_get_res,
		adder_match_exponents_num1,
		adder_match_exponents_num2;
  wire adder_EN_add_mantissa,
       adder_EN_clear_adder,
       adder_EN_match_exponents,
       adder_EN_normalise,
       adder_state_1_done,
       adder_state_2_done,
       adder_state_3_done;

  // rule scheduling signals
  wire CAN_FIRE_RL_init_v,
       CAN_FIRE_RL_loop_rule,
       CAN_FIRE_RL_print_rule,
       CAN_FIRE_get_n_and_m_loaded,
       CAN_FIRE_n_and_m_load,
       CAN_FIRE_send_bt_data,
       CAN_FIRE_send_curr_data,
       CAN_FIRE_send_emission_data,
       CAN_FIRE_send_outcome_data,
       CAN_FIRE_send_prev_data,
       CAN_FIRE_send_transition_data,
       CAN_FIRE_set_read_transition,
       WILL_FIRE_RL_init_v,
       WILL_FIRE_RL_loop_rule,
       WILL_FIRE_RL_print_rule,
       WILL_FIRE_get_n_and_m_loaded,
       WILL_FIRE_n_and_m_load,
       WILL_FIRE_send_bt_data,
       WILL_FIRE_send_curr_data,
       WILL_FIRE_send_emission_data,
       WILL_FIRE_send_outcome_data,
       WILL_FIRE_send_prev_data,
       WILL_FIRE_send_transition_data,
       WILL_FIRE_set_read_transition;

  // inputs to muxes for submodule ports
  reg [3 : 0] MUX_machine_state_write_1__VAL_3;
  reg [1 : 0] MUX_init_state_write_1__VAL_2;
  wire [31 : 0] MUX_adder_match_exponents_1__VAL_2,
		MUX_adder_match_exponents_2__VAL_2,
		MUX_max_reg_write_1__VAL_2;
  wire [9 : 0] MUX_t_ctr_write_1__VAL_1;
  wire [4 : 0] MUX_i_ctr_write_1__VAL_1,
	       MUX_i_ctr_write_1__VAL_2,
	       MUX_i_ctr_write_1__VAL_3,
	       MUX_j_ctr_write_1__VAL_2,
	       MUX_max_state_reg_write_1__VAL_2;
  wire [1 : 0] MUX_print_state_write_1__VAL_3;
  wire MUX_adder_match_exponents_1__SEL_1,
       MUX_i_ctr_write_1__SEL_1,
       MUX_i_ctr_write_1__SEL_2,
       MUX_i_ctr_write_1__SEL_3,
       MUX_init_done_flag_write_1__SEL_1,
       MUX_loop_done_flag_write_1__SEL_1,
       MUX_machine_state_write_1__SEL_1,
       MUX_machine_state_write_1__SEL_3,
       MUX_print_state_write_1__SEL_1,
       MUX_print_state_write_1__SEL_3,
       MUX_read_emission_write_1__SEL_3,
       MUX_read_transition_write_1__SEL_3,
       MUX_t_ctr_write_1__SEL_3,
       MUX_write_to_prev_flag_write_1__SEL_1;

  // remaining internal signals
  wire [9 : 0] x__h3674, x__h4224, x__h4978, x__h4994;
  wire [4 : 0] x__h3046, x__h4041, y__h3548;
  wire NOT_machine_state_9_EQ_1_6_00_AND_NOT_machine__ETC___d155,
       NOT_machine_state_9_EQ_1_6_00_AND_NOT_machine__ETC___d179,
       NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d114,
       NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d169,
       NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d192,
       _dand1adder_EN_normalise,
       _dand2adder_EN_clear_adder,
       _dfoo1,
       _dfoo3,
       adder_state_1_done__3_AND_adder_state_2_done___ETC___d56,
       adder_state_3_done__5_AND_adder_get_res__1_ULT_ETC___d148,
       i_ctr_6_ULT_n_reg_7_MINUS_1_8_9_AND_curr_ready_ETC___d224,
       i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29,
       init_state_EQ_0_AND_outcome_ready_OR_NOT_init__ETC___d36,
       init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d21,
       init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d70,
       init_state_EQ_1_0_AND_outcome_buffer_1_EQ_0_2__ETC___d58,
       init_state_EQ_2_2_AND_adder_state_1_done__3_AN_ETC___d46,
       j_ctr_21_ULT_n_reg_7_MINUS_1_8___d122,
       machine_state_9_EQ_1_6_AND_NOT_outcome_buffer__ETC___d135,
       machine_state_9_EQ_1_6_AND_outcome_buffer_1_EQ_ETC___d117,
       machine_state_9_EQ_3_04_AND_prev_ready_05_AND__ETC___d184,
       machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110,
       prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d106,
       prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d151,
       print_state_17_EQ_0_18_AND_i_ctr_6_ULT_n_reg_7_ETC___d271,
       print_state_17_EQ_1_29_AND_NOT_bt_t_ctr_30_EQ__ETC___d244;

  // actionvalue method get_n_and_m_loaded
  assign get_n_and_m_loaded = n_and_m_loaded ;
  assign RDY_get_n_and_m_loaded = 1'd1 ;
  assign CAN_FIRE_get_n_and_m_loaded = 1'd1 ;
  assign WILL_FIRE_get_n_and_m_loaded = EN_get_n_and_m_loaded ;

  // action method n_and_m_load
  assign RDY_n_and_m_load = 1'd1 ;
  assign CAN_FIRE_n_and_m_load = 1'd1 ;
  assign WILL_FIRE_n_and_m_load = EN_n_and_m_load ;

  // value method read_outcome_idx
  assign read_outcome_idx = outcome_idx ;
  assign RDY_read_outcome_idx = 1'd1 ;

  // action method send_transition_data
  assign RDY_send_transition_data = 1'd1 ;
  assign CAN_FIRE_send_transition_data = 1'd1 ;
  assign WILL_FIRE_send_transition_data = EN_send_transition_data ;

  // action method send_emission_data
  assign RDY_send_emission_data = 1'd1 ;
  assign CAN_FIRE_send_emission_data = 1'd1 ;
  assign WILL_FIRE_send_emission_data = EN_send_emission_data ;

  // action method send_outcome_data
  assign RDY_send_outcome_data = 1'd1 ;
  assign CAN_FIRE_send_outcome_data = 1'd1 ;
  assign WILL_FIRE_send_outcome_data = EN_send_outcome_data ;

  // value method get_read_transition
  assign get_read_transition = read_transition ;
  assign RDY_get_read_transition = 1'd1 ;

  // action method set_read_transition
  assign RDY_set_read_transition = 1'd1 ;
  assign CAN_FIRE_set_read_transition = 1'd1 ;
  assign WILL_FIRE_set_read_transition = EN_set_read_transition ;

  // value method get_read_emission
  assign get_read_emission = read_emission ;
  assign RDY_get_read_emission = 1'd1 ;

  // value method get_read_outcome
  assign get_read_outcome = read_outcome ;
  assign RDY_get_read_outcome = 1'd1 ;

  // value method get_reset_decoder
  assign get_reset_decoder = reset_machine_flag ;
  assign RDY_get_reset_decoder = 1'd1 ;

  // value method get_print_state
  assign get_print_state = print_state ;
  assign RDY_get_print_state = 1'd1 ;

  // value method get_num_obs
  assign get_num_obs = x__h4978[5:0] ;
  assign RDY_get_num_obs = 1'd1 ;

  // value method get_probab
  assign get_probab = bt_max ;
  assign RDY_get_probab = 1'd1 ;

  // value method get_init_done_flag
  assign get_init_done_flag = init_done_flag ;
  assign RDY_get_init_done_flag = 1'd1 ;

  // value method get_i_ctr
  assign get_i_ctr = i_ctr ;
  assign RDY_get_i_ctr = 1'd1 ;

  // value method get_j_ctr
  assign get_j_ctr = j_ctr ;
  assign RDY_get_j_ctr = 1'd1 ;

  // value method get_outcome
  assign get_outcome = outcome_buffer ;
  assign RDY_get_outcome = 1'd1 ;

  // value method get_write_to_bt_flag
  assign get_write_to_bt_flag = write_to_bt_flag ;
  assign RDY_get_write_to_bt_flag = 1'd1 ;

  // value method get_max_stage_reg
  assign get_max_stage_reg = max_state_reg ;
  assign RDY_get_max_stage_reg = 1'd1 ;

  // value method get_read_bt
  assign get_read_bt = read_bt ;
  assign RDY_get_read_bt = 1'd1 ;

  // value method get_bt_t_ctr
  assign get_bt_t_ctr = bt_t_ctr ;
  assign RDY_get_bt_t_ctr = 1'd1 ;

  // action method send_bt_data
  assign RDY_send_bt_data = 1'd1 ;
  assign CAN_FIRE_send_bt_data = 1'd1 ;
  assign WILL_FIRE_send_bt_data = EN_send_bt_data ;

  // value method get_path_buffer
  assign get_path_buffer = path_buffer ;
  assign RDY_get_path_buffer = 1'd1 ;

  // value method get_path_ready
  assign get_path_ready = path_ready ;
  assign RDY_get_path_ready = 1'd1 ;

  // value method get_curr_buffer
  assign get_curr_buffer = curr_buffer ;
  assign RDY_get_curr_buffer = 1'd1 ;

  // value method get_write_to_curr_flag
  assign get_write_to_curr_flag = write_to_curr_flag ;
  assign RDY_get_write_to_curr_flag = 1'd1 ;

  // value method get_read_curr
  assign get_read_curr = read_curr ;
  assign RDY_get_read_curr = 1'd1 ;

  // value method get_read_prev
  assign get_read_prev = read_prev ;
  assign RDY_get_read_prev = 1'd1 ;

  // action method send_prev_data
  assign RDY_send_prev_data = 1'd1 ;
  assign CAN_FIRE_send_prev_data = 1'd1 ;
  assign WILL_FIRE_send_prev_data = EN_send_prev_data ;

  // action method send_curr_data
  assign RDY_send_curr_data = 1'd1 ;
  assign CAN_FIRE_send_curr_data = 1'd1 ;
  assign WILL_FIRE_send_curr_data = EN_send_curr_data ;

  // value method get_switch_prev_curr
  assign get_switch_prev_curr = switch_prev_curr ;
  assign RDY_get_switch_prev_curr = 1'd1 ;

  // value method get_write_to_prev_flag
  assign get_write_to_prev_flag = write_to_prev_flag ;
  assign RDY_get_write_to_prev_flag = 1'd1 ;

  // value method get_prev_buffer
  assign get_prev_buffer = prev_buffer ;
  assign RDY_get_prev_buffer = 1'd1 ;

  // submodule adder
  mkFP32_Adder adder(.CLK(CLK),
		     .RST_N(RST_N),
		     .match_exponents_num1(adder_match_exponents_num1),
		     .match_exponents_num2(adder_match_exponents_num2),
		     .EN_match_exponents(adder_EN_match_exponents),
		     .EN_add_mantissa(adder_EN_add_mantissa),
		     .EN_normalise(adder_EN_normalise),
		     .EN_clear_adder(adder_EN_clear_adder),
		     .RDY_match_exponents(),
		     .RDY_add_mantissa(),
		     .RDY_normalise(),
		     .get_res(adder_get_res),
		     .RDY_get_res(),
		     .state_1_done(adder_state_1_done),
		     .RDY_state_1_done(),
		     .state_2_done(adder_state_2_done),
		     .RDY_state_2_done(),
		     .state_3_done(adder_state_3_done),
		     .RDY_state_3_done(),
		     .RDY_clear_adder());

  // rule RL_init_v
  assign CAN_FIRE_RL_init_v = !init_done_flag && n_and_m_loaded ;
  assign WILL_FIRE_RL_init_v = CAN_FIRE_RL_init_v ;

  // rule RL_loop_rule
  assign CAN_FIRE_RL_loop_rule = init_done_flag && !loop_done_flag ;
  assign WILL_FIRE_RL_loop_rule = CAN_FIRE_RL_loop_rule ;

  // rule RL_print_rule
  assign CAN_FIRE_RL_print_rule = loop_done_flag && init_done_flag ;
  assign WILL_FIRE_RL_print_rule = CAN_FIRE_RL_print_rule ;

  // inputs to muxes for submodule ports
  assign MUX_adder_match_exponents_1__SEL_1 =
	     WILL_FIRE_RL_init_v && init_state == 2'd2 &&
	     !adder_state_1_done ;
  assign MUX_i_ctr_write_1__SEL_1 =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_2_2_AND_adder_state_1_done__3_AN_ETC___d46 ;
  assign MUX_i_ctr_write_1__SEL_2 =
	     WILL_FIRE_RL_loop_rule &&
	     (machine_state == 4'd6 || machine_state == 4'd7) ;
  assign MUX_i_ctr_write_1__SEL_3 =
	     WILL_FIRE_RL_print_rule &&
	     (print_state == 2'd0 && i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 &&
	      curr_ready ||
	      print_state == 2'd2) ;
  assign MUX_init_done_flag_write_1__SEL_1 =
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ;
  assign MUX_loop_done_flag_write_1__SEL_1 =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd7 ;
  assign MUX_machine_state_write_1__SEL_1 =
	     WILL_FIRE_RL_init_v && init_state == 2'd2 &&
	     adder_state_1_done__3_AND_adder_state_2_done___ETC___d56 ;
  assign MUX_machine_state_write_1__SEL_3 =
	     WILL_FIRE_RL_loop_rule &&
	     (machine_state == 4'd0 && outcome_ready ||
	      machine_state != 4'd0 &&
	      machine_state_9_EQ_1_6_AND_outcome_buffer_1_EQ_ETC___d117) ;
  assign MUX_print_state_write_1__SEL_1 =
	     WILL_FIRE_RL_init_v && init_state == 2'd1 &&
	     outcome_buffer == 32'd0 &&
	     t_ctr != 10'd0 ;
  assign MUX_print_state_write_1__SEL_3 =
	     WILL_FIRE_RL_print_rule &&
	     (print_state == 2'd0 && !i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ||
	      print_state == 2'd1 && bt_t_ctr == 10'd0) ;
  assign MUX_read_emission_write_1__SEL_3 =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d70 ;
  assign MUX_read_transition_write_1__SEL_3 =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd2 &&
	     !read_transition &&
	     !transition_ready ;
  assign MUX_t_ctr_write_1__SEL_3 =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd6 &&
	     !i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ;
  assign MUX_write_to_prev_flag_write_1__SEL_1 =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd0 ;
  assign MUX_adder_match_exponents_1__VAL_2 =
	     (machine_state == 4'd3) ? prev_buffer : max_reg ;
  assign MUX_adder_match_exponents_2__VAL_2 =
	     (machine_state == 4'd3) ? transition_buffer : emission_buffer ;
  assign MUX_i_ctr_write_1__VAL_1 =
	     i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ? x__h4041 : 5'd0 ;
  assign MUX_i_ctr_write_1__VAL_2 =
	     (machine_state == 4'd6) ?
	       (i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ? x__h4041 : 5'd0) :
	       5'd0 ;
  assign MUX_i_ctr_write_1__VAL_3 = (print_state == 2'd0) ? x__h4041 : 5'd0 ;
  always@(init_state)
  begin
    case (init_state)
      2'd0: MUX_init_state_write_1__VAL_2 = 2'd1;
      2'd1: MUX_init_state_write_1__VAL_2 = 2'd2;
      default: MUX_init_state_write_1__VAL_2 = 2'd1;
    endcase
  end
  assign MUX_j_ctr_write_1__VAL_2 =
	     (machine_state == 4'd3) ? x__h3046 : 5'd0 ;
  always@(machine_state or
	  i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 or
	  outcome_buffer or j_ctr_21_ULT_n_reg_7_MINUS_1_8___d122)
  begin
    case (machine_state)
      4'd0: MUX_machine_state_write_1__VAL_3 = 4'd1;
      4'd1:
	  MUX_machine_state_write_1__VAL_3 =
	      (outcome_buffer == 32'hFFFFFFFF) ? 4'd7 : 4'd2;
      4'd2: MUX_machine_state_write_1__VAL_3 = 4'd3;
      4'd3:
	  MUX_machine_state_write_1__VAL_3 =
	      j_ctr_21_ULT_n_reg_7_MINUS_1_8___d122 ? 4'd2 : 4'd5;
      4'd5: MUX_machine_state_write_1__VAL_3 = 4'd6;
      default: MUX_machine_state_write_1__VAL_3 =
		   i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ? 4'd1 : 4'd0;
    endcase
  end
  assign MUX_max_reg_write_1__VAL_2 =
	     (machine_state == 4'd3) ? adder_get_res : 32'hFFFFFFFF ;
  assign MUX_max_state_reg_write_1__VAL_2 =
	     (machine_state == 4'd3) ? j_ctr : 5'd0 ;
  assign MUX_print_state_write_1__VAL_3 =
	     (print_state == 2'd0) ? 2'd1 : 2'd2 ;
  assign MUX_t_ctr_write_1__VAL_1 = t_ctr + 10'd1 ;

  // register bt_buffer
  assign bt_buffer_D_IN = send_bt_data_data ;
  assign bt_buffer_EN = EN_send_bt_data ;

  // register bt_max
  assign bt_max_D_IN = (print_state == 2'd0) ? curr_buffer : 32'hFFFFFFFF ;
  assign bt_max_EN =
	     WILL_FIRE_RL_print_rule &&
	     (print_state == 2'd0 &&
	      i_ctr_6_ULT_n_reg_7_MINUS_1_8_9_AND_curr_ready_ETC___d224 ||
	      print_state == 2'd2) ;

  // register bt_ready
  assign bt_ready_D_IN = EN_send_bt_data ;
  assign bt_ready_EN =
	     WILL_FIRE_RL_print_rule && print_state == 2'd1 &&
	     bt_t_ctr != 10'd0 &&
	     bt_ready ||
	     EN_send_bt_data ;

  // register bt_t_ctr
  assign bt_t_ctr_D_IN = (print_state == 2'd0) ? x__h3674 : x__h4224 ;
  assign bt_t_ctr_EN =
	     WILL_FIRE_RL_print_rule &&
	     (print_state == 2'd0 && !i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ||
	      print_state == 2'd1 && bt_t_ctr != 10'd0 && bt_ready) ;

  // register curr_buffer
  assign curr_buffer_D_IN =
	     EN_send_curr_data ? send_curr_data_data : adder_get_res ;
  assign curr_buffer_EN =
	     WILL_FIRE_RL_loop_rule &&
	     machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110 ||
	     EN_send_curr_data ;

  // register curr_ready
  assign curr_ready_D_IN = EN_send_curr_data ;
  assign curr_ready_EN =
	     WILL_FIRE_RL_print_rule && print_state == 2'd0 &&
	     i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 &&
	     curr_ready ||
	     EN_send_curr_data ;

  // register emission_buffer
  assign emission_buffer_D_IN = send_emission_data_data ;
  assign emission_buffer_EN = EN_send_emission_data ;

  // register emission_ready
  assign emission_ready_D_IN = EN_send_emission_data ;
  assign emission_ready_EN =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d21 ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd1 &&
	     outcome_buffer != 32'hFFFFFFFF &&
	     emission_ready ||
	     EN_send_emission_data ;

  // register i_ctr
  always@(MUX_i_ctr_write_1__SEL_1 or
	  MUX_i_ctr_write_1__VAL_1 or
	  MUX_i_ctr_write_1__SEL_2 or
	  MUX_i_ctr_write_1__VAL_2 or
	  MUX_i_ctr_write_1__SEL_3 or MUX_i_ctr_write_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_i_ctr_write_1__SEL_1: i_ctr_D_IN = MUX_i_ctr_write_1__VAL_1;
      MUX_i_ctr_write_1__SEL_2: i_ctr_D_IN = MUX_i_ctr_write_1__VAL_2;
      MUX_i_ctr_write_1__SEL_3: i_ctr_D_IN = MUX_i_ctr_write_1__VAL_3;
      default: i_ctr_D_IN = 5'bxxxxx /* unspecified value */ ;
    endcase
  end
  assign i_ctr_EN =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_2_2_AND_adder_state_1_done__3_AN_ETC___d46 ||
	     WILL_FIRE_RL_loop_rule &&
	     (machine_state == 4'd6 || machine_state == 4'd7) ||
	     MUX_i_ctr_write_1__SEL_3 ;

  // register init_done_flag
  assign init_done_flag_D_IN = !MUX_init_done_flag_write_1__SEL_1 ;
  assign init_done_flag_EN =
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ||
	     WILL_FIRE_RL_init_v && init_state != 2'd0 &&
	     init_state_EQ_1_0_AND_outcome_buffer_1_EQ_0_2__ETC___d58 ;

  // register init_state
  assign init_state_D_IN =
	     MUX_init_done_flag_write_1__SEL_1 ?
	       2'd0 :
	       MUX_init_state_write_1__VAL_2 ;
  assign init_state_EN =
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ||
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_0_AND_outcome_ready_OR_NOT_init__ETC___d36 ;

  // register j_ctr
  assign j_ctr_D_IN =
	     MUX_init_done_flag_write_1__SEL_1 ?
	       5'd0 :
	       MUX_j_ctr_write_1__VAL_2 ;
  assign j_ctr_EN =
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ||
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     machine_state != 4'd1 &&
	     NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d169 ;

  // register loop_done_flag
  assign loop_done_flag_D_IN =
	     MUX_loop_done_flag_write_1__SEL_1 || init_state == 2'd1 ;
  assign loop_done_flag_EN =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd7 ||
	     WILL_FIRE_RL_init_v && init_state != 2'd0 &&
	     init_state_EQ_1_0_AND_outcome_buffer_1_EQ_0_2__ETC___d58 ;

  // register m_reg
  assign m_reg_D_IN = n_and_m_load_m ;
  assign m_reg_EN = EN_n_and_m_load ;

  // register machine_state
  assign machine_state_D_IN =
	     MUX_machine_state_write_1__SEL_3 ?
	       MUX_machine_state_write_1__VAL_3 :
	       4'd0 ;
  assign machine_state_EN =
	     WILL_FIRE_RL_init_v && init_state == 2'd2 &&
	     adder_state_1_done__3_AND_adder_state_2_done___ETC___d56 ||
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ||
	     MUX_machine_state_write_1__SEL_3 ;

  // register max_path
  assign max_path_D_IN = (print_state == 2'd0) ? x__h4041 : bt_buffer ;
  assign max_path_EN =
	     WILL_FIRE_RL_print_rule &&
	     (print_state == 2'd0 &&
	      i_ctr_6_ULT_n_reg_7_MINUS_1_8_9_AND_curr_ready_ETC___d224 ||
	      print_state == 2'd1 && bt_t_ctr != 10'd0 && bt_ready) ;

  // register max_reg
  assign max_reg_D_IN =
	     MUX_init_done_flag_write_1__SEL_1 ?
	       32'hFFFFFFFF :
	       MUX_max_reg_write_1__VAL_2 ;
  assign max_reg_EN =
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ||
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     NOT_machine_state_9_EQ_1_6_00_AND_NOT_machine__ETC___d155 ;

  // register max_state_reg
  assign max_state_reg_D_IN =
	     MUX_init_done_flag_write_1__SEL_1 ?
	       5'd0 :
	       MUX_max_state_reg_write_1__VAL_2 ;
  assign max_state_reg_EN =
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ||
	     WILL_FIRE_RL_loop_rule &&
	     (machine_state == 4'd3 &&
	      prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d151 ||
	      machine_state == 4'd6) ;

  // register n_and_m_loaded
  assign n_and_m_loaded_D_IN = 1'd1 ;
  assign n_and_m_loaded_EN = EN_n_and_m_load ;

  // register n_reg
  assign n_reg_D_IN = n_and_m_load_n ;
  assign n_reg_EN = EN_n_and_m_load ;

  // register outcome_buffer
  assign outcome_buffer_D_IN = send_outcome_data_data ;
  assign outcome_buffer_EN = EN_send_outcome_data ;

  // register outcome_idx
  assign outcome_idx_D_IN = t_ctr ;
  assign outcome_idx_EN =
	     WILL_FIRE_RL_init_v && init_state == 2'd0 && !read_outcome &&
	     !outcome_ready ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd0 &&
	     !read_outcome &&
	     !outcome_ready ;

  // register outcome_ready
  assign outcome_ready_D_IN = EN_send_outcome_data ;
  assign outcome_ready_EN =
	     WILL_FIRE_RL_init_v && init_state == 2'd0 && outcome_ready ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd0 &&
	     outcome_ready ||
	     EN_send_outcome_data ;

  // register path_buffer
  assign path_buffer_D_IN =
	     (print_state == 2'd0 &&
	      i_ctr_6_ULT_n_reg_7_MINUS_1_8_9_AND_curr_ready_ETC___d224 ||
	      print_state_17_EQ_1_29_AND_NOT_bt_t_ctr_30_EQ__ETC___d244) ?
	       ((print_state == 2'd0) ? x__h4041 : max_path) :
	       bt_buffer ;
  assign path_buffer_EN = WILL_FIRE_RL_print_rule && _dfoo3 ;

  // register path_ready
  assign path_ready_D_IN =
	     (print_state != 2'd0 || i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29) &&
	     (print_state == 2'd0 ||
	      !print_state_17_EQ_1_29_AND_NOT_bt_t_ctr_30_EQ__ETC___d244 &&
	      print_state != 2'd2) ||
	     print_state == 2'd0 ;
  assign path_ready_EN = WILL_FIRE_RL_print_rule && _dfoo1 ;

  // register prev_buffer
  assign prev_buffer_D_IN =
	     EN_send_prev_data ? send_prev_data_data : adder_get_res ;
  assign prev_buffer_EN =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_2_2_AND_adder_state_1_done__3_AN_ETC___d46 ||
	     EN_send_prev_data ;

  // register prev_ready
  assign prev_ready_D_IN = EN_send_prev_data ;
  assign prev_ready_EN =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd3 && prev_ready ||
	     EN_send_prev_data ;

  // register print_state
  always@(MUX_print_state_write_1__SEL_1 or
	  MUX_loop_done_flag_write_1__SEL_1 or
	  MUX_print_state_write_1__SEL_3 or MUX_print_state_write_1__VAL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_print_state_write_1__SEL_1: print_state_D_IN = 2'd3;
      MUX_loop_done_flag_write_1__SEL_1: print_state_D_IN = 2'd0;
      MUX_print_state_write_1__SEL_3:
	  print_state_D_IN = MUX_print_state_write_1__VAL_3;
      default: print_state_D_IN = 2'bxx /* unspecified value */ ;
    endcase
  end
  assign print_state_EN =
	     WILL_FIRE_RL_init_v && init_state == 2'd1 &&
	     outcome_buffer == 32'd0 &&
	     t_ctr != 10'd0 ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd7 ||
	     MUX_print_state_write_1__SEL_3 ;

  // register read_bt
  assign read_bt_D_IN = !EN_send_bt_data ;
  assign read_bt_EN =
	     WILL_FIRE_RL_print_rule &&
	     print_state_17_EQ_1_29_AND_NOT_bt_t_ctr_30_EQ__ETC___d244 ||
	     EN_send_bt_data ;

  // register read_curr
  assign read_curr_D_IN = !EN_send_curr_data ;
  assign read_curr_EN =
	     WILL_FIRE_RL_print_rule &&
	     print_state_17_EQ_0_18_AND_i_ctr_6_ULT_n_reg_7_ETC___d271 ||
	     EN_send_curr_data ;

  // register read_emission
  assign read_emission_D_IN = !EN_send_emission_data ;
  assign read_emission_EN =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d70 ||
	     WILL_FIRE_RL_loop_rule &&
	     machine_state_9_EQ_1_6_AND_NOT_outcome_buffer__ETC___d135 ||
	     EN_send_emission_data ;

  // register read_outcome
  assign read_outcome_D_IN = !EN_send_outcome_data ;
  assign read_outcome_EN =
	     WILL_FIRE_RL_init_v && init_state == 2'd0 && !read_outcome &&
	     !outcome_ready ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd0 &&
	     !read_outcome &&
	     !outcome_ready ||
	     EN_send_outcome_data ;

  // register read_prev
  assign read_prev_D_IN = !EN_send_prev_data ;
  assign read_prev_EN =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd3 && !read_prev &&
	     !prev_ready ||
	     EN_send_prev_data ;

  // register read_transition
  always@(EN_set_read_transition or
	  set_read_transition_val or
	  EN_send_transition_data or
	  MUX_read_transition_write_1__SEL_3 or
	  MUX_read_emission_write_1__SEL_3)
  case (1'b1)
    EN_set_read_transition: read_transition_D_IN = set_read_transition_val;
    EN_send_transition_data: read_transition_D_IN = 1'd0;
    MUX_read_transition_write_1__SEL_3 || MUX_read_emission_write_1__SEL_3:
	read_transition_D_IN = 1'd1;
    default: read_transition_D_IN = 1'bx /* unspecified value */ ;
  endcase
  assign read_transition_EN =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d70 ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd2 &&
	     !read_transition &&
	     !transition_ready ||
	     EN_set_read_transition ||
	     EN_send_transition_data ;

  // register reset_machine_flag
  assign reset_machine_flag_D_IN = 1'd1 ;
  assign reset_machine_flag_EN =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd1 &&
	     outcome_buffer == 32'hFFFFFFFF ;

  // register switch_prev_curr
  assign switch_prev_curr_D_IN = machine_state != 4'd0 ;
  assign switch_prev_curr_EN =
	     WILL_FIRE_RL_loop_rule &&
	     (machine_state == 4'd0 ||
	      machine_state == 4'd6 && !i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29) ;

  // register t_ctr
  always@(MUX_machine_state_write_1__SEL_1 or
	  MUX_t_ctr_write_1__VAL_1 or
	  MUX_init_done_flag_write_1__SEL_1 or MUX_t_ctr_write_1__SEL_3)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_machine_state_write_1__SEL_1: t_ctr_D_IN = MUX_t_ctr_write_1__VAL_1;
      MUX_init_done_flag_write_1__SEL_1:
	  t_ctr_D_IN = MUX_t_ctr_write_1__VAL_1;
      MUX_t_ctr_write_1__SEL_3: t_ctr_D_IN = MUX_t_ctr_write_1__VAL_1;
      default: t_ctr_D_IN = 10'bxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign t_ctr_EN =
	     WILL_FIRE_RL_init_v && init_state == 2'd2 &&
	     adder_state_1_done__3_AND_adder_state_2_done___ETC___d56 ||
	     WILL_FIRE_RL_print_rule && print_state == 2'd2 ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd6 &&
	     !i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ;

  // register t_start
  assign t_start_D_IN = MUX_t_ctr_write_1__VAL_1 ;
  assign t_start_EN = MUX_init_done_flag_write_1__SEL_1 ;

  // register transition_buffer
  assign transition_buffer_D_IN = send_transition_data_data ;
  assign transition_buffer_EN = EN_send_transition_data ;

  // register transition_ready
  assign transition_ready_D_IN = EN_send_transition_data ;
  assign transition_ready_EN =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d21 ||
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd2 &&
	     transition_ready ||
	     EN_send_transition_data ;

  // register write_to_bt_flag
  assign write_to_bt_flag_D_IN = machine_state == 4'd5 ;
  assign write_to_bt_flag_EN =
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     machine_state != 4'd1 &&
	     machine_state != 4'd2 &&
	     machine_state != 4'd3 &&
	     (machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110 ||
	      machine_state == 4'd6) ;

  // register write_to_curr_flag
  assign write_to_curr_flag_D_IN = machine_state == 4'd5 ;
  assign write_to_curr_flag_EN =
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     machine_state != 4'd1 &&
	     machine_state != 4'd2 &&
	     machine_state != 4'd3 &&
	     (machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110 ||
	      machine_state == 4'd6) ;

  // register write_to_prev_flag
  assign write_to_prev_flag_D_IN =
	     !MUX_write_to_prev_flag_write_1__SEL_1 && init_state != 2'd1 ;
  assign write_to_prev_flag_EN =
	     WILL_FIRE_RL_loop_rule && machine_state == 4'd0 ||
	     WILL_FIRE_RL_init_v && init_state != 2'd0 &&
	     (init_state == 2'd1 ||
	      init_state_EQ_2_2_AND_adder_state_1_done__3_AN_ETC___d46) ;

  // submodule adder
  assign adder_match_exponents_num1 =
	     MUX_adder_match_exponents_1__SEL_1 ?
	       transition_buffer :
	       MUX_adder_match_exponents_1__VAL_2 ;
  assign adder_match_exponents_num2 =
	     MUX_adder_match_exponents_1__SEL_1 ?
	       emission_buffer :
	       MUX_adder_match_exponents_2__VAL_2 ;
  assign adder_EN_match_exponents =
	     WILL_FIRE_RL_init_v && init_state == 2'd2 &&
	     !adder_state_1_done ||
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     machine_state != 4'd1 &&
	     NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d192 ;
  assign adder_EN_add_mantissa =
	     WILL_FIRE_RL_init_v && init_state == 2'd2 &&
	     adder_state_1_done &&
	     !adder_state_2_done ||
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     machine_state != 4'd1 &&
	     machine_state != 4'd2 &&
	     machine_state_9_EQ_3_04_AND_prev_ready_05_AND__ETC___d184 ;
  assign adder_EN_normalise =
	     _dand1adder_EN_normalise ||
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     NOT_machine_state_9_EQ_1_6_00_AND_NOT_machine__ETC___d179 ;
  assign adder_EN_clear_adder =
	     WILL_FIRE_RL_init_v &&
	     init_state_EQ_2_2_AND_adder_state_1_done__3_AN_ETC___d46 ||
	     _dand2adder_EN_clear_adder ;

  // remaining internal signals
  assign NOT_machine_state_9_EQ_1_6_00_AND_NOT_machine__ETC___d155 =
	     machine_state != 4'd1 && machine_state != 4'd2 &&
	     (machine_state == 4'd3 &&
	      prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d151 ||
	      machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110) ;
  assign NOT_machine_state_9_EQ_1_6_00_AND_NOT_machine__ETC___d179 =
	     machine_state == 4'd3 && prev_ready && adder_state_1_done &&
	     adder_state_2_done &&
	     !adder_state_3_done ||
	     machine_state == 4'd5 && adder_state_1_done &&
	     adder_state_2_done &&
	     !adder_state_3_done ;
  assign NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d114 =
	     machine_state != 4'd2 &&
	     (machine_state == 4'd3 &&
	      prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d106 ||
	      machine_state != 4'd3 &&
	      (machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110 ||
	       machine_state == 4'd6)) ;
  assign NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d169 =
	     machine_state == 4'd3 && prev_ready && adder_state_1_done &&
	     adder_state_2_done &&
	     adder_state_3_done &&
	     j_ctr_21_ULT_n_reg_7_MINUS_1_8___d122 ||
	     machine_state == 4'd5 ;
  assign NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d192 =
	     machine_state == 4'd3 && prev_ready && !adder_state_1_done ||
	     machine_state == 4'd5 && !adder_state_1_done ;
  assign _dand1adder_EN_normalise =
	     WILL_FIRE_RL_init_v && init_state == 2'd2 &&
	     adder_state_1_done &&
	     adder_state_2_done &&
	     !adder_state_3_done ;
  assign _dand2adder_EN_clear_adder =
	     WILL_FIRE_RL_loop_rule && machine_state != 4'd0 &&
	     machine_state != 4'd1 &&
	     machine_state != 4'd2 &&
	     (machine_state == 4'd3 &&
	      prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d106 ||
	      machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110) ;
  assign _dfoo1 =
	     print_state == 2'd0 && !i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ||
	     print_state != 2'd0 &&
	     (print_state_17_EQ_1_29_AND_NOT_bt_t_ctr_30_EQ__ETC___d244 ||
	      print_state == 2'd2) ||
	     print_state == 2'd1 && bt_t_ctr != 10'd0 && bt_ready ;
  assign _dfoo3 =
	     print_state == 2'd0 &&
	     i_ctr_6_ULT_n_reg_7_MINUS_1_8_9_AND_curr_ready_ETC___d224 ||
	     print_state_17_EQ_1_29_AND_NOT_bt_t_ctr_30_EQ__ETC___d244 ||
	     print_state == 2'd1 && bt_t_ctr != 10'd0 && bt_ready ;
  assign adder_state_1_done__3_AND_adder_state_2_done___ETC___d56 =
	     adder_state_1_done && adder_state_2_done && adder_state_3_done &&
	     !i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 ;
  assign adder_state_3_done__5_AND_adder_get_res__1_ULT_ETC___d148 =
	     adder_state_3_done && adder_get_res < max_reg && j_ctr < n_reg ;
  assign i_ctr_6_ULT_n_reg_7_MINUS_1_8_9_AND_curr_ready_ETC___d224 =
	     i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 && curr_ready &&
	     curr_buffer < bt_max ;
  assign i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 = i_ctr < y__h3548 ;
  assign init_state_EQ_0_AND_outcome_ready_OR_NOT_init__ETC___d36 =
	     init_state == 2'd0 && outcome_ready ||
	     init_state != 2'd0 &&
	     (init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d21 ||
	      init_state == 2'd2 && adder_state_1_done &&
	      adder_state_2_done &&
	      adder_state_3_done &&
	      i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29) ;
  assign init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d21 =
	     init_state == 2'd1 &&
	     (outcome_buffer != 32'd0 || t_ctr == 10'd0) &&
	     transition_ready &&
	     emission_ready ;
  assign init_state_EQ_1_0_AND_NOT_outcome_buffer_1_EQ__ETC___d70 =
	     init_state == 2'd1 &&
	     (outcome_buffer != 32'd0 || t_ctr == 10'd0) &&
	     !transition_ready &&
	     !read_transition &&
	     !emission_ready &&
	     !read_emission ;
  assign init_state_EQ_1_0_AND_outcome_buffer_1_EQ_0_2__ETC___d58 =
	     init_state == 2'd1 && outcome_buffer == 32'd0 &&
	     t_ctr != 10'd0 ||
	     init_state == 2'd2 &&
	     adder_state_1_done__3_AND_adder_state_2_done___ETC___d56 ;
  assign init_state_EQ_2_2_AND_adder_state_1_done__3_AN_ETC___d46 =
	     init_state == 2'd2 && adder_state_1_done && adder_state_2_done &&
	     adder_state_3_done ;
  assign j_ctr_21_ULT_n_reg_7_MINUS_1_8___d122 = j_ctr < y__h3548 ;
  assign machine_state_9_EQ_1_6_AND_NOT_outcome_buffer__ETC___d135 =
	     machine_state == 4'd1 && outcome_buffer != 32'hFFFFFFFF &&
	     !read_emission &&
	     !emission_ready ;
  assign machine_state_9_EQ_1_6_AND_outcome_buffer_1_EQ_ETC___d117 =
	     machine_state == 4'd1 &&
	     (outcome_buffer == 32'hFFFFFFFF || emission_ready) ||
	     machine_state != 4'd1 &&
	     (machine_state == 4'd2 && transition_ready ||
	      NOT_machine_state_9_EQ_2_01_03_AND_machine_sta_ETC___d114) ;
  assign machine_state_9_EQ_3_04_AND_prev_ready_05_AND__ETC___d184 =
	     machine_state == 4'd3 && prev_ready && adder_state_1_done &&
	     !adder_state_2_done ||
	     machine_state == 4'd5 && adder_state_1_done &&
	     !adder_state_2_done ;
  assign machine_state_9_EQ_5_09_AND_adder_state_1_done_ETC___d110 =
	     machine_state == 4'd5 && adder_state_1_done &&
	     adder_state_2_done &&
	     adder_state_3_done ;
  assign prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d106 =
	     prev_ready && adder_state_1_done && adder_state_2_done &&
	     adder_state_3_done ;
  assign prev_ready_05_AND_adder_state_1_done__3_AND_ad_ETC___d151 =
	     prev_ready && adder_state_1_done && adder_state_2_done &&
	     adder_state_3_done__5_AND_adder_get_res__1_ULT_ETC___d148 ;
  assign print_state_17_EQ_0_18_AND_i_ctr_6_ULT_n_reg_7_ETC___d271 =
	     print_state == 2'd0 && i_ctr_6_ULT_n_reg_7_MINUS_1_8___d29 &&
	     !read_curr &&
	     !curr_ready ;
  assign print_state_17_EQ_1_29_AND_NOT_bt_t_ctr_30_EQ__ETC___d244 =
	     print_state == 2'd1 && bt_t_ctr != 10'd0 && !read_bt &&
	     !bt_ready ;
  assign x__h3046 = j_ctr + 5'd1 ;
  assign x__h3674 = x__h4994 - 10'd1 ;
  assign x__h4041 = i_ctr + 5'd1 ;
  assign x__h4224 = bt_t_ctr - 10'd1 ;
  assign x__h4978 = x__h4994 + 10'd1 ;
  assign x__h4994 = t_ctr - t_start ;
  assign y__h3548 = n_reg - 5'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        bt_buffer <= `BSV_ASSIGNMENT_DELAY 5'd0;
	bt_max <= `BSV_ASSIGNMENT_DELAY 32'hFFFFFFFF;
	bt_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	bt_t_ctr <= `BSV_ASSIGNMENT_DELAY 10'd0;
	curr_buffer <= `BSV_ASSIGNMENT_DELAY 32'd0;
	curr_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	emission_buffer <= `BSV_ASSIGNMENT_DELAY 32'd0;
	emission_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	i_ctr <= `BSV_ASSIGNMENT_DELAY 5'd0;
	init_done_flag <= `BSV_ASSIGNMENT_DELAY 1'd0;
	init_state <= `BSV_ASSIGNMENT_DELAY 2'd0;
	j_ctr <= `BSV_ASSIGNMENT_DELAY 5'd0;
	loop_done_flag <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_reg <= `BSV_ASSIGNMENT_DELAY 5'd0;
	machine_state <= `BSV_ASSIGNMENT_DELAY 4'd0;
	max_path <= `BSV_ASSIGNMENT_DELAY 5'd0;
	max_reg <= `BSV_ASSIGNMENT_DELAY 32'hFFFFFFFF;
	max_state_reg <= `BSV_ASSIGNMENT_DELAY 5'd0;
	n_and_m_loaded <= `BSV_ASSIGNMENT_DELAY 1'd0;
	n_reg <= `BSV_ASSIGNMENT_DELAY 5'd0;
	outcome_buffer <= `BSV_ASSIGNMENT_DELAY 32'd0;
	outcome_idx <= `BSV_ASSIGNMENT_DELAY 10'd0;
	outcome_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	path_buffer <= `BSV_ASSIGNMENT_DELAY 5'd0;
	path_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	prev_buffer <= `BSV_ASSIGNMENT_DELAY 32'd0;
	prev_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	print_state <= `BSV_ASSIGNMENT_DELAY 2'd0;
	read_bt <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_curr <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_emission <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_outcome <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_prev <= `BSV_ASSIGNMENT_DELAY 1'd0;
	read_transition <= `BSV_ASSIGNMENT_DELAY 1'd0;
	reset_machine_flag <= `BSV_ASSIGNMENT_DELAY 1'd0;
	switch_prev_curr <= `BSV_ASSIGNMENT_DELAY 1'd0;
	t_ctr <= `BSV_ASSIGNMENT_DELAY 10'd0;
	t_start <= `BSV_ASSIGNMENT_DELAY 10'd0;
	transition_buffer <= `BSV_ASSIGNMENT_DELAY 32'd0;
	transition_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
	write_to_bt_flag <= `BSV_ASSIGNMENT_DELAY 1'd0;
	write_to_curr_flag <= `BSV_ASSIGNMENT_DELAY 1'd0;
	write_to_prev_flag <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (bt_buffer_EN) bt_buffer <= `BSV_ASSIGNMENT_DELAY bt_buffer_D_IN;
	if (bt_max_EN) bt_max <= `BSV_ASSIGNMENT_DELAY bt_max_D_IN;
	if (bt_ready_EN) bt_ready <= `BSV_ASSIGNMENT_DELAY bt_ready_D_IN;
	if (bt_t_ctr_EN) bt_t_ctr <= `BSV_ASSIGNMENT_DELAY bt_t_ctr_D_IN;
	if (curr_buffer_EN)
	  curr_buffer <= `BSV_ASSIGNMENT_DELAY curr_buffer_D_IN;
	if (curr_ready_EN)
	  curr_ready <= `BSV_ASSIGNMENT_DELAY curr_ready_D_IN;
	if (emission_buffer_EN)
	  emission_buffer <= `BSV_ASSIGNMENT_DELAY emission_buffer_D_IN;
	if (emission_ready_EN)
	  emission_ready <= `BSV_ASSIGNMENT_DELAY emission_ready_D_IN;
	if (i_ctr_EN) i_ctr <= `BSV_ASSIGNMENT_DELAY i_ctr_D_IN;
	if (init_done_flag_EN)
	  init_done_flag <= `BSV_ASSIGNMENT_DELAY init_done_flag_D_IN;
	if (init_state_EN)
	  init_state <= `BSV_ASSIGNMENT_DELAY init_state_D_IN;
	if (j_ctr_EN) j_ctr <= `BSV_ASSIGNMENT_DELAY j_ctr_D_IN;
	if (loop_done_flag_EN)
	  loop_done_flag <= `BSV_ASSIGNMENT_DELAY loop_done_flag_D_IN;
	if (m_reg_EN) m_reg <= `BSV_ASSIGNMENT_DELAY m_reg_D_IN;
	if (machine_state_EN)
	  machine_state <= `BSV_ASSIGNMENT_DELAY machine_state_D_IN;
	if (max_path_EN) max_path <= `BSV_ASSIGNMENT_DELAY max_path_D_IN;
	if (max_reg_EN) max_reg <= `BSV_ASSIGNMENT_DELAY max_reg_D_IN;
	if (max_state_reg_EN)
	  max_state_reg <= `BSV_ASSIGNMENT_DELAY max_state_reg_D_IN;
	if (n_and_m_loaded_EN)
	  n_and_m_loaded <= `BSV_ASSIGNMENT_DELAY n_and_m_loaded_D_IN;
	if (n_reg_EN) n_reg <= `BSV_ASSIGNMENT_DELAY n_reg_D_IN;
	if (outcome_buffer_EN)
	  outcome_buffer <= `BSV_ASSIGNMENT_DELAY outcome_buffer_D_IN;
	if (outcome_idx_EN)
	  outcome_idx <= `BSV_ASSIGNMENT_DELAY outcome_idx_D_IN;
	if (outcome_ready_EN)
	  outcome_ready <= `BSV_ASSIGNMENT_DELAY outcome_ready_D_IN;
	if (path_buffer_EN)
	  path_buffer <= `BSV_ASSIGNMENT_DELAY path_buffer_D_IN;
	if (path_ready_EN)
	  path_ready <= `BSV_ASSIGNMENT_DELAY path_ready_D_IN;
	if (prev_buffer_EN)
	  prev_buffer <= `BSV_ASSIGNMENT_DELAY prev_buffer_D_IN;
	if (prev_ready_EN)
	  prev_ready <= `BSV_ASSIGNMENT_DELAY prev_ready_D_IN;
	if (print_state_EN)
	  print_state <= `BSV_ASSIGNMENT_DELAY print_state_D_IN;
	if (read_bt_EN) read_bt <= `BSV_ASSIGNMENT_DELAY read_bt_D_IN;
	if (read_curr_EN) read_curr <= `BSV_ASSIGNMENT_DELAY read_curr_D_IN;
	if (read_emission_EN)
	  read_emission <= `BSV_ASSIGNMENT_DELAY read_emission_D_IN;
	if (read_outcome_EN)
	  read_outcome <= `BSV_ASSIGNMENT_DELAY read_outcome_D_IN;
	if (read_prev_EN) read_prev <= `BSV_ASSIGNMENT_DELAY read_prev_D_IN;
	if (read_transition_EN)
	  read_transition <= `BSV_ASSIGNMENT_DELAY read_transition_D_IN;
	if (reset_machine_flag_EN)
	  reset_machine_flag <= `BSV_ASSIGNMENT_DELAY reset_machine_flag_D_IN;
	if (switch_prev_curr_EN)
	  switch_prev_curr <= `BSV_ASSIGNMENT_DELAY switch_prev_curr_D_IN;
	if (t_ctr_EN) t_ctr <= `BSV_ASSIGNMENT_DELAY t_ctr_D_IN;
	if (t_start_EN) t_start <= `BSV_ASSIGNMENT_DELAY t_start_D_IN;
	if (transition_buffer_EN)
	  transition_buffer <= `BSV_ASSIGNMENT_DELAY transition_buffer_D_IN;
	if (transition_ready_EN)
	  transition_ready <= `BSV_ASSIGNMENT_DELAY transition_ready_D_IN;
	if (write_to_bt_flag_EN)
	  write_to_bt_flag <= `BSV_ASSIGNMENT_DELAY write_to_bt_flag_D_IN;
	if (write_to_curr_flag_EN)
	  write_to_curr_flag <= `BSV_ASSIGNMENT_DELAY write_to_curr_flag_D_IN;
	if (write_to_prev_flag_EN)
	  write_to_prev_flag <= `BSV_ASSIGNMENT_DELAY write_to_prev_flag_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    bt_buffer = 5'h0A;
    bt_max = 32'hAAAAAAAA;
    bt_ready = 1'h0;
    bt_t_ctr = 10'h2AA;
    curr_buffer = 32'hAAAAAAAA;
    curr_ready = 1'h0;
    emission_buffer = 32'hAAAAAAAA;
    emission_ready = 1'h0;
    i_ctr = 5'h0A;
    init_done_flag = 1'h0;
    init_state = 2'h2;
    j_ctr = 5'h0A;
    loop_done_flag = 1'h0;
    m_reg = 5'h0A;
    machine_state = 4'hA;
    max_path = 5'h0A;
    max_reg = 32'hAAAAAAAA;
    max_state_reg = 5'h0A;
    n_and_m_loaded = 1'h0;
    n_reg = 5'h0A;
    outcome_buffer = 32'hAAAAAAAA;
    outcome_idx = 10'h2AA;
    outcome_ready = 1'h0;
    path_buffer = 5'h0A;
    path_ready = 1'h0;
    prev_buffer = 32'hAAAAAAAA;
    prev_ready = 1'h0;
    print_state = 2'h2;
    read_bt = 1'h0;
    read_curr = 1'h0;
    read_emission = 1'h0;
    read_outcome = 1'h0;
    read_prev = 1'h0;
    read_transition = 1'h0;
    reset_machine_flag = 1'h0;
    switch_prev_curr = 1'h0;
    t_ctr = 10'h2AA;
    t_start = 10'h2AA;
    transition_buffer = 32'hAAAAAAAA;
    transition_ready = 1'h0;
    write_to_bt_flag = 1'h0;
    write_to_curr_flag = 1'h0;
    write_to_prev_flag = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkViterbi

